### ISSUE TITLE
Footprint Review Analysis - Footprint Ratio analysis (SOW Task 2.2)

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#102]
Splitting this out from #100 

The ratio of gross square footage to footprint area task:
1. From footprints, we'd need to calculate the area in Square Feet.
2. Then join in the `reported_gross_floor_area` from the data at https://cityenergy-seattle.carto.com/dataset/seattle_buildings_2022_update.
3. Then calculate the ratio `reported_gross_floor_area/footprint_area`

Us the same data as in this comment https://github.com/GreenInfo-Network/seattle-building-dashboard/issues/100#issuecomment-2153395022

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1207509538911620)

**Comment by joseph-stout** [comment]
on our call in a bit can you point me to the correct dataset to get _reported_gross_floor_area_? I am not seeing it in the linked file or anywhere else on carto

**Comment by danrademacher** [comment]
To get the data we need out of CARTO, we used this query:

```sql
SELECT outlines.buildingid, tabular.reported_gross_floor_area
FROM public.data_2022_update as tabular
JOIN public.seattle_building_outlines_2022 as outlines
on outlines.buildingid = tabular.id
```

Joseph to export that and do the rest in GIS and Excel

That's here https://cityenergy-seattle.carto.com/dataset/seattle_building_outlines_2022 (at least until the query above gets cleared in CARTO)

**Comment by joseph-stout** [comment]
P:\proj_p_s\Seattle Building Dashboard\2024_update\Reported_Gross_vs_Footprint_Analysis

Pulled down the table with buildingid and reported_gross_area from carto using the query above. Joined to seattle_buildings_2022_update_mr_20240425_v21 file with calculated footprint_area field in square feet. Then created a new field called gross_ratio and calculated as reported_gross_floor_area/footprint_area. Results are in the link to P drive above. Note there are some Null values, but these were present in the source reporte_gross_floor area table as well.

**Comment by danrademacher** [comment]
Some issues after client review of this table:
https://docs.google.com/spreadsheets/d/12lx-0MOmYFDnQDeLz87yhyexZhHUu1Ru/edit?gid=374649775#gid=374649775

Looks like most of the issues arise out of buildings that are multipolygons with small extra shapes. We need to add up the area of all the polygons in a building and use that as the basis for the ratio

**Comment by danrademacher** [comment]
Looking at the data, it appears these are polygons and not multipolygons, so we need dissolve based on `buildingid`

**Comment by danrademacher** [comment]
Just replace the table in this folder:
https://drive.google.com/drive/folders/1WTkAe5bo9G2efz6XXZcFzUVGvXUyP4Om

**Comment by joseph-stout** [comment]
Updating here-- I went back through this yesterday and got buildingID's for the overlaps. Working through re-calculating the area. I had done a dissolve in the previous workflow, but now sorting through why that didn't produce the correct outcome and if I need to change a setting or change what stage in the process the dissolve occurs.

**Comment by joseph-stout** [comment]
I went back and re-did my workflow yesterday to try to assess where things went awry with the calculations. I couldn't see any errors in the calculation after the dissolve, so went back and checked some of the raw numbers. I am a bit stumped, as there are cases where the GIS area and the reported gross area are vastly different, even accounting for the individual polygons.

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/144196585/9dffe148-899e-4050-92ff-decc08ee44d1)

For buildingid 465, there are two polygons with area of 398sqft and 48,587sqft respectively. The dissolved buildingid area calculation appears correct at 48,985. The reported gross floor area is 287,819sqft. So from the beginning, I can't see a way the sum will be equivalent. There are other cases of this as well, I updated the table with the new calculations which should be more accurate generally, but there remain a number of cases I am not clear on how to resolve. And, I am now curiou where the reported_gross_footprint_area is coming from.

**Comment by joseph-stout** [comment]
Here is another example. buildingid 518 has only one record and is identified as the small building in the upper right-hand corner. Buildingid 519 is adjacent. According to the data we pulled down from carto, buildingid 518 has a reported square footage of 114,000 square feet. The GIS calculation lands at 174 sq ft., which is quite small but judgin from the aerial imagery may be roughly accurate. The adjacent building, id# 519, has a reported square footage of 50,083. The GIS calculation is 120,144. I am going to check on the website to try to see what is going on and if these discrepancies are present on the dashboard.

**Comment by joseph-stout** [comment]
Okay getting some clarity now. I looked up buildingid 518 in cartodb and the address on Google went here: 13200 AURORA AVE N

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/144196585/7fc37ffa-6f4b-4de0-bc77-71a6da59e992)
Which was assigned to buildingid 518 in the GIS data. The discrepancy then would be ~6000 ft sq. which is probably resolved by editing the building footprint more accurately.

BuildingId 519 in cartodb was assigned 21236 in the GIS data. The calculated area is 53,786, which would be much closer to the 50,083 figure from gross_reported_square_feet. So there is some misalignment in how the buildingid is being assigned, which is why the calculations are so broken. I am not sure how to resolve this issue so far.

**Comment by danrademacher** [comment]
Based on discussion:
* 518 and 519 actually seem like a real example of bad data we want to highlight for Mike.
* For others, we can improve result by correcting for `numfloors`

running this query:
```sql
SELECT outlines.the_geom,outlines.buildingid, tabular.reported_gross_floor_area, tabular.numfloors
FROM public.seattle_buildings_2022_update_copy as tabular
JOIN public.seattle_building_outlines_2022 as outlines
on outlines.buildingid = tabular.id
where tabular.year = 2022
```
https://cityenergy-seattle.carto.com/dataset/seattle_building_outlines_2022

Next steps:
* For any row where `numfloors>0`, divide the `reported_gross_floor_area` by `numfloors`  to get `single_gross_floor_area` and use that for the ratio.
* For rows where `numfloors=0` just use the raw `reported_gross_floor_area` for the ratio.

**Comment by joseph-stout** [comment]
The table is updated. In some cases the number of floors seems to have caused the calculation to overshoot the reported footprint area somewhat significantly, but overall there appear to be a more reasonable number of outliers.

**Comment by danrademacher** [comment]
@joseph-stout I'd like to clarify the definitions/math used to explain this to the client

- `reported_gross_area` -- this is from the tabular data as reported by Seattle
- `Calculated Total Footprint Area` -- I am no sure what this is. **What is the math here?**
- `Building Footprint Area Ratio` -- I think this is `Footprint_area (GIS)/(reported_gross_area/Num_floors` but want to be sure
- `Footprint_area (GIS)` -- this square feet is calculated in GIS from footprints
- `Shape Length` -- not sure what this is. It was hidden. **Can we delete it from the table?**
- `Num_floors`  -- this is from the tabular data as reported by Seattle

**Comment by joseph-stout** [comment]
Finished the ratio analysis and cleaned up some outliers/oddities (ex: num_floors and gross_reported_area were null). Some issues appeared to occur where id's had been deprecated but not removed, and conflicted with the updated id's. There were also a few instances where duplication occurred due to mis-placed centroids in the spatial join (< 20), so I manually fixed those by cross-referencing with the footprints on the city energy website. This did not lead to a clean match for some of the calculated values vs reported area estimates, but did at least ensure the correct footprint geometry was assigned and num_floors was accurate.

**Comment by joseph-stout** [comment]
> @joseph-stout I'd like to clarify the definitions/math used to explain this to the client
> 
> * `reported_gross_area` -- this is from the tabular data as reported by Seattle
> * `Calculated Total Footprint Area` -- I am no sure what this is. **What is the math here?**
> * `Building Footprint Area Ratio` -- I think this is `Footprint_area (GIS)/(reported_gross_area/Num_floors` but want to be sure
> * `Footprint_area (GIS)` -- this square feet is calculated in GIS from footprints
> * `Shape Length` -- not sure what this is. It was hidden. **Can we delete it from the table?**
> * `Num_floors`  -- this is from the tabular data as reported by Seattle

Yes sorry, to clarify--
reported_gross_area = from the provided tabular data
Calculated Total Area Footprint = GIS area (from footprint polygon geometry) * num_floors (reported by Seattle)
Building Footprint Area Ratio = Calculated Total Area Footprint / Reported Gross Area (to assess how closely the GIS calculations match the reported areas- i.e. deviations from 1.0 in either direction indicate greater disagreement between the GIS figures and reported figures)
Footprint Area (GIS) = calculated geometry from building footprints in the GIS, using Seattle/King County standard projection
Shape_length-- that was an artifact, I have removed this.
Num_floors - yes, reported via Seattle

**Comment by danrademacher** [comment]
I'm seeing some more issues here related to zeros in the numfloors and nulls in both numfloors and reported_gross_area

* These IDs show as 0 for `numfloors`  267, 656, 657, 758, 23311, 40031, 40034, 50549. This is expected since the data includes 131 records where numfloors = zero. However, we can't just apply `Footprint Area (GIS)` times `numfloors` in these cases, since we then get 0. Wherever we have 0 in `numfloors`, we should instead treat it as `1`.
* I was going to just fix that in Excel but then I noticed that we also have [138 records](https://docs.google.com/spreadsheets/d/1-Cer1CH33_t7-SA150D-8x8fVPPalBlY/edit?gid=1170502007#gid=1170502007) where the `reported_gross_area` is null in the excel table, and then the `Building Footprint Area Ratio` is also null.

I am not sure where those are coming from. Oddly, I ran the query below using the 138 `buildingid` values from Excel where we show `<Null>` for reported gross area, and I got only 8 results and all had values for the `reported gross area`

```sql
SELECT outlines.the_geom,outlines.buildingid, tabular.reported_gross_floor_area, tabular.numfloors
FROM public.seattle_buildings_2022_update_copy as tabular
JOIN public.seattle_building_outlines_2022 as outlines
on outlines.buildingid = tabular.id
where tabular.year = 2022 and buildingid in (25,31,46,67,170,50689,347,416,50376,98,484,508,517,522,545,555,557,586,29214,642,704,731,785,790,847,19624,19656,19658,19718,19744,19798,19835,19833,19845,19862,19882,19896,19907,19926,19927,19928,20059,20211,20301,20302,20376,20525,20556,20617,20618,20815,21237,21327,21373,21396,50863,21459,21546,21578,21656,21716,21879,22172,22441,22519,23065,23158,23293,23308,23313,23404,50735,23701,23848,23861,23912,23930,24077,24083,24117,24374,24498,24605,24725,24726,24778,24805,24825,24895,24896,24904,24943,24955,25025,50694,25148,25250,25455,25567,25635,25654,25709,25711,25821,26095,26182,26319,26392,26396,26529,26535,26681,26908,27244,27355,27604,27639,27987,28045,28064,621,33548,34908,867,41927,49715,49769,49799,49859,49924,49925,49926,49970,49977,49979,49980,49982,50058,50069,23022,19876,560,838,24408,50660,187,228,195)
```

I am still puzzling where those odd records are coming from.

I assume your process looked like this:
1. Download the data as noted in [this comment](https://github.com/GreenInfo-Network/seattle-building-dashboard/issues/102#issuecomment-2207377291)
2. Calculate the area of the geometry in square feet
3. Multiply that by `numfloor`  -- **here's where we need a conditional to avoid multiplying by 0**
4. Divide the result of 3 by `reported_gross-area` to get the ratio

I am not sure where in that process we could get nulls or have IDs introduced for buildings that were not in the original set downloaded in 1.

**Comment by danrademacher** [comment]
Perhaps the best way forward here would be to limit work in GIS to only "Calculate the area of the geometry in square feet" -- the rest we could do in Excel/Sheets and then it will be more obvious what's going on in those math operations.

**Comment by joseph-stout** [comment]
That is strange. I think it's a continuation of the issue with the points generated not being placed in the polygons in some cases, so the spatial join misses it. I thought it was specific to duplicates. Agree that going about it in GIS has been convoluted and going forward in Excel may be an improvement. I'll start this today but likely won't be able to finish until next week due to being out.

**Comment by danrademacher** [comment]
My next call with the client is Wednesday of next week (7/18), so ideally we could get him a revised set by then.

Regarding points in polygons, I am not sure why you needed to generate points or do a join since the last export form CARTO included the footprint geometry. 

In any case, I think the process now should be to just add a `footprint_area` column in Square Feet to an export of this query from [this CARTO table](https://cityenergy-seattle.carto.com/dataset/seattle_building_outlines_2022)
```sql
SELECT outlines.the_geom,outlines.buildingid, tabular.reported_gross_floor_area, tabular.numfloors
FROM public.seattle_buildings_2022_update_copy as tabular
JOIN public.seattle_building_outlines_2022 as outlines
on outlines.buildingid = tabular.id
where tabular.year = 2022
```

Then expoirt as CSV without geometry and load that in Google Sheets so we can do the rest of the math there.

**Comment by joseph-stout** [comment]
Okay, I will make sure to have it done before then. I can explain what happened, but I am not sure why. When I downloaded the file with the reported gross area and num_floors columns  it was a point .shp with no geometry, so I did a spatial join to the existing polygon layer with the new point layer to pull in those attributes with the GIS footprint area calculations However I did not anticipate there would be issues with the points not landing within the existing polygons, which I believe is where the null values originated. 

But yes going forward I will just stick to using Google Sheets and do the math in there as you say.

**Comment by joseph-stout** [comment]
Alright. I think I cleaned things up, No null values that I can see and the calculations seem to make more sense in general. 3636 unique building id's which seems slightly less than what I remember but unsure how to confirm. I will review some of the outliers later in the week to see if it looks like bad data or a calculation error. Updated tab with the date is [here]((https://docs.google.com/spreadsheets/d/1-Cer1CH33_t7-SA150D-8x8fVPPalBlY/edit?gid=1576608023#gid=1576608023)

**Comment by danrademacher** [comment]
Ok, great! Let's have you walk through the final table above with @AmandaGIN on Monday

**Comment by joseph-stout** [comment]
@AmandaGIN I am having issues getting carto to load the data (simiilar to the issues we had with the map drawing earlier), but the raw .shp (not dissolved) with building_id, num_floors, and reported_gross_area is here: 
P:\proj_p_s\Seattle Building Dashboard\2024_update\seattle_building_outlines_2022_UPDATED

In case you need it, the data from my GIS calulations (only geoprocessing was to dissolve by building_id to aggregate multipolygons) is here:
P:\proj_p_s\Seattle Building Dashboard\2024_update\seattle_buildings_ftprnt_ratio_final\seattle_buildings_ftprnt_ratio_final

And the link to the google sheet is here:
https://docs.google.com/spreadsheets/d/1-Cer1CH33_t7-SA150D-8x8fVPPalBlY/edit?gid=1576608023#gid=1576608023

The num_floors with value of 1 highlighted in yellow are converted from original value of zero. 
The building_id's highlighted in green are known to have overlaps from the other task in 2.2

Thanks for going over this with me, let me know if you have any other questions.

**Comment by AmandaGIN** [comment]
Poking around in the original data to make sure I fully understand it.
There are 4,608 polygons, but `buldingid` is not unique, when summarized, there are 3,636 unique `buildingid` values.
The max is 120 for multi-part (all in a geographic cluster - over University of Washington campus),  most of the next big ones (15-27 parts) are housing (colleges, apt complexes, etc) one exception is `buldingid` = 172 25 parts, all one Public Storage unit.

If you Summarized by `buldingid` it's okay to take min/max of `numfloors' - tested and there are no deviations, if a building id repeats, it always reports the same number of floors.
11 building ids have 0 floors (assigned 1)

**Comment by AmandaGIN** [comment]
Spot checks, look at a few random table rows and see if they align to expected results if I reference the GIS data:

Building ID | AK sq ft match | notes
--- | --- | --- | 
27554 | yes | Our data is 3.5x higher

**Comment by AmandaGIN** [comment]
overall, run calcs since they are quick (in my GIS copy) and compare totals/counts:
- merge/diss to multi-part
- if 0 floors, set 1

**Comment by AmandaGIN** [comment]
This sheet is now ready @danrademacher 
https://docs.google.com/spreadsheets/d/1-Cer1CH33_t7-SA150D-8x8fVPPalBlY/edit?gid=1576608023#gid=1576608023

There is a field description at: https://docs.google.com/spreadsheets/d/1-Cer1CH33_t7-SA150D-8x8fVPPalBlY/edit?gid=418313610#gid=418313610

The one oddity we noted is that 26 building id's were in a previous version of the data and are no longer in the download. We believe this is correct, because they also do not appear on the website. You can see the list of those 26 at: https://docs.google.com/spreadsheets/d/1-Cer1CH33_t7-SA150D-8x8fVPPalBlY/edit?gid=625440939#gid=625440939
marked in column d "not in last data download"

**Comment by danrademacher** [comment]
Delivered this to client via their Sharepoint. In their hands now to determine if we fix any footprints based on this info.
