### ISSUE TITLE
Add two new footprints to GIS footprint update in process

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#106]
Over in #99 we have a bunch of footprint updates in midflight.

Once those are done, we need to be sure to also drop in these two new footprints that Tom digitized:
https://github.com/GreenInfo-Network/seattle-building-dashboard/issues/105#issuecomment-2221604767

Then the GIS file can be a full replacement for what's on CARTO.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1207782640487119)

**Comment by joseph-stout** [comment]
I completed the footprint updates and merged the two additional polygons for building id 50755 and 19863. Final shapefile is here:

P:\proj_p_s\Seattle Building Dashboard\2024_update\seattle_building_outlines_2024_update\seattle_building_outlines_2024_update
