### ISSUE TITLE
Scope out main map changes

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#11]
* Implement multiple navigation changes, including left navigation simplification and improvement.
* Add one GHG metric to popup for selected building

It looks like we make these changes in the config file.

Order of map layers on the home page look like they can be changed here:
https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L86-L215

Popup here:
https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L66-L84

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201488554970406)

**Comment by danrademacher** [comment]
For the weather normalized change:
> Good question on the _wn change. If it’s relatively straightforward to switch to two main parts of the map that would be best. If not, let me know and we can discuss.

![image](https://user-images.githubusercontent.com/1423200/145286710-caf9aa2a-b402-49ba-88fc-a2653595af10.png)

**Comment by danrademacher** [comment]
Hold on this till everything else is done

**Comment by tomay** [comment]
Question on this comment: 
> Add one GHG metric to popup for selected building

Seems like we'd want that for the selected year, and then that would go into this section? 
![image](https://user-images.githubusercontent.com/740512/147124658-36a132fa-3b2d-4059-aa80-6c44390ad6f5.png)

So that's not a `seattle.json` change per se, instead seems this is a new measure that would need to be integrated into the template, the number needs to be colored according to its rank, etc.  

Is there a section that corresponds to this on the left sidebar? If this corresponds to the cards on the report, then the field is `total_ghg_emissions_intensity `

**Comment by danrademacher** [comment]
@seattle-benchmarking since we have some time today, should we go ahead with these main map changes?

That would look like:
1. Move the GHG section in left bar to the top and make "Total Seattle GHG Emissions" the default layer
![image](https://user-images.githubusercontent.com/1423200/147126635-51820dbe-a15f-4a13-a456-976c77d91985.png)
2. Change the use of weather-normalized as described in this comment, https://github.com/GreenInfo-Network/seattle-building-dashboard/issues/11#issuecomment-989208592

About @tomay's [last comment above](https://github.com/GreenInfo-Network/seattle-building-dashboard/issues/11#issuecomment-999717087) about a new GHG measure in the popup, I think we're best off leaving that as `wont-fix` for this phase since it would require reworking the template and likely a taller popup that might cause other issues.

**Comment by tomay** [comment]
Looks like there are several places in `seattle.json` where we could update measures to use "weather normalized" EUI: 

### Popup
* `site_eui` to `site_eui_wn` in [popup_chart.lead](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L68)

### Map Layers/Sidebar
* `site_eui` to `site_eui_wn` in [Building EUI Quartiles](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L131)
* `site_eui` to `site_eui_wn` in [Site Energy Use Intensity](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L158)
* `source_eui` to `source_eui_wn` in [Source Energy Use Intensity](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L170)

**Comment by seattle-benchmarking** [comment]
sorry just saw this. @danrademacher I agree that adding the new GHG measure to the popup can wait until next year.

if you end up making changes to the sidebar, the following make sense to me:

1. Move the GHG section in left bar to the top and make "Total Seattle GHG Emissions" the default layer per @danrademacher comment
2. Change to `site_eui_wn` for the (1) popup, (2) sidebar quartiles and sidebar EUI
3. Suppress/hide Source EUI and Site Total Energy Use layers
4. Order sidebar buckets in reverse of current (Greenhouse Gas Emissions, Energy Perf Metrics, Property Info)

-

**Comment by danrademacher** [comment]
@tomay this branch has the changes that achieve layer ordering and default layer, but not the `wn` changes

https://github.com/GreenInfo-Network/seattle-building-dashboard/commit/f62778378ef222d02e73756a8b7eca9c8fdcfe51

**Comment by tomay** [comment]
I believe this is done, please reopen if there is anything more to do

**Comment by seattle-benchmarking** [comment]
@danrademacher @tomay Could you replace the Site Total Energy Use layer with the Site EUI one?

**Comment by danrademacher** [comment]
Deployed to GH pages:
![image](https://user-images.githubusercontent.com/1423200/148819766-43c4ec1b-7faf-492c-ad2c-92f190c5f5ab.png)

This can be updated in the production code simply by replacing this file:
`cities/seattle.json`

With the file at https://raw.githubusercontent.com/GreenInfo-Network/seattle-building-dashboard/master/src/cities/seattle.json
