### ISSUE TITLE
New text for out of compliance buildings

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#112]
From Mike:

> Here is what I’m proposing for the update to the non-compliant property messaging. This will simplify things for us because the state-owned buildings – which are not required to comply with benchmarking – can now have the **same, softer messaging as the non-state buildings**. We should keep the building report greyed out for properties with incomplete data.
>  
> Existing:
> Out of Compliance
> As of the last quarterly update to this map, the City of Seattle has not received complete, valid benchmarking data for this property in this reporting year. If this is your property, please visit the [Energy Benchmarking Instructions page](https://www.seattle.gov/environment/climate-change/buildings-and-energy/energy-benchmarking/instructions) or contact [energybenchmarking@seattle.gov](mailto:energybenchmarking@seattle.gov) to bring it into compliance.
>  
> Proposed:
> Incomplete Data
> As of the latest update to this map, the City of Seattle has not received complete, valid benchmarking data for this property for the specified reporting year. If this is your property, please visit the [Energy Benchmarking Instructions page](https://www.seattle.gov/environment/climate-change/buildings-and-energy/energy-benchmarking/instructions) or contact [energybenchmarking@seattle.gov](mailto:energybenchmarking@seattle.gov) for more information about how to comply with Seattle’ Energy Benchmarking Law.

This sounds simple to change, though I don't recall the details of state-owned vs non-state-owned v incomplete data properties.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208064546845422)

**Comment by tomay** [comment]
Looks like a missing `s` on `Seattle'`

**Comment by tomay** [comment]
I have not changed any logic relating to which message is displayed, but simply replaced the old text (one matching instance I could find) with this new text
