### ISSUE TITLE
The search function is generally a little buggy.

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#114]
Seems like two issues:

- [x] Min character for string match conflicts with short building IDs:

> There are one and two digit OSEIDs (not a great data management practice, but that pre-dated me by a decade) and the properties with those one and two digit IDs (i.e. 22) don’t populate when you enter them in the search bar. This seems unfair to the owner of OSEID 5.

- [ ] Default Search results selection is inconsistent:

>When you enter an ID number and then hit the enter button, it sometimes, but not always brings you to the top result in the list. I’m not sure why this only works some of the time. Can you investigate?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208064509387901)

**Comment by danrademacher** [comment]
Reducing the minchar for search actually seems just fine in my local testing. The deploy script is failing for me right now, so I can't push it up for Mike to see.

I'll file a separate ticket on that deploy issue for tracking (not critical though slightly worrisome if deploy doesn't consistently work)

**Comment by tomay** [comment]
I've run the deploy script so the proposed fix for the first issue should soon be available on GH pages

**Comment by tomay** [comment]
In terms of the second issue, I need additional information
- It would be helpful to have an example of a building ID where this is an issue, as well as a more detailed sequence of actions leading to the reported bug 
- When I search for a building by ID and hit the enter button, I don't get taken to any result; instead, I get the following view of "Nearby buildings..." 

![image](https://github.com/user-attachments/assets/6176e1de-848f-4f30-8097-52377cc6dd6d)

To be clear, I have no idea what that is trying to do, but also I don't understand how to reproduce the original bug as reported

**Comment by tomay** [comment]
Something else I just discovered, if you search for a building by ID, scroll down the list, _hover_ over one of the entries, then click enter - that building gets selected. 

Very custom (and non-standard?) behavior for a dropdown list

I always simply click an entry in the list, and this always takes me directly to that result

**Comment by danrademacher** [comment]
Mike says this is fine as is.
