### ISSUE TITLE
Relocate filter toggles for reduced screen clutter

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#117]
- [x] Move "Show All Buildings" to main nav and ~rename as Property Type~
- [x] Make the timeline a dropdown

See discussion on the request to "rename as property type" below. 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208163962222605)

**Comment by tomay** [comment]
It's been fairly easy to get here, but I'm also remembering some discussion with the client about other options (mutli-select, or a dropdown containing checkboxes, etc.)

![image](https://github.com/user-attachments/assets/89f82b5e-6015-44bb-858d-77400d6e2834)

Right now these are just straight-up selects, using "Selectize" - an ancient synthetic dropdown generator, which is already in use in the application. 

If instead, these should be more like the Neighborhood and Council dropdowns, which are kind of custom dropdown/combo-boxes, then more discussion is needed

**Comment by danrademacher** [comment]
Note from mike:
* Year selector option should list year options descending, so most recent year comes first.

**Comment by tomay** [comment]
One issue I just noticed with the building type selector. When "High-rise Multifamily" is selected, it doesn't fit: 

![image](https://github.com/user-attachments/assets/21f2891f-2296-4198-a0de-36a41689635c)

**Comment by tomay** [comment]
This is all set
