### ISSUE TITLE
Improve cross hatch pattern fill for non‐compliant buildings 

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#119]
> Improve cross hatch pattern fill for non‐compliant buildings that is more compatible with zooming in and out

Try a single hatch style, not double hatch as currently implemented

Hatch images are defined here: 
https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/app/views/map/building_layer.js#L33-L44

And currently saved to S3 here: 
https://seattle-buildings-polygon-hatch-images.s3.us-west-1.amazonaws.com/hatch_double_cross_grey_45_narrow_thin_transparent.png

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208171475446162)

**Comment by tomay** [comment]
With Tim's help, added a new single hatch fill with a tighter pattern. 

It's relatively dense at high zooms: 

![image](https://github.com/user-attachments/assets/4d39b877-87a5-4e90-90dc-1120e14e4695)

But this helps single out non-compliant buildings at low zoom. Here's the last step before we show points: 

![image](https://github.com/user-attachments/assets/7e836512-82a2-443e-a5c6-db5d5a59c4b6)

**Comment by danrademacher** [comment]
* Mike asked about the possibility of zoom-dependent styling
* Worried about the “vibration” of the hatching as we zoom in

So we need to rediscover how to do zoom dependent styling in CartoCSS. There's a simple example here:
https://cartocss.readthedocs.io/en/latest/styling_concepts.html#nested-styles

```css
[zoom > 1] {
  /* Applies to all layers at zoom > 1 */
  polygon-gamma: 0.3;
  #world {
    polygon-fill: #323;
  }
  #lakes {
    polygon-fill: #144;
  }
}
```

**Comment by tomay** [comment]
Here's the existing CartoCSS passed to Carto: 

```
#benchmarking_production {polygon-fill: #CCC;polygon-opacity: 0.9;line-width: 1;line-color: #FFF;line-opacity: 0.5;polygon-pattern-file: url(https://seattle-buildings-polygon-hatch-images.s3.us-west-1.amazonaws.com/seamless_hatch_2x.png);polygon-pattern-opacity: 1;}
#benchmarking_production [total_ghg_emissions>=1]{polygon-fill:#1f5dbe; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=2]{polygon-fill:#306fa5; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=3]{polygon-fill:#40808c; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=4]{polygon-fill:#519273; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=5]{polygon-fill:#6ba165; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=7]{polygon-fill:#90ae60; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=12]{polygon-fill:#b5bb5b; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=18]{polygon-fill:#dac857; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=24]{polygon-fill:#ffd552; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=32]{polygon-fill:#f7c34e; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=41.44444444444457]{polygon-fill:#efb24a; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=54]{polygon-fill:#e6a045; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=68]{polygon-fill:#de8f41; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=86]{polygon-fill:#d57b3c; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=112]{polygon-fill:#ca6537; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=148.16666666666697]{polygon-fill:#c04f32; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=224]{polygon-fill:#b5392d; polygon-pattern-opacity: 0;}
#benchmarking_production [total_ghg_emissions>=378]{polygon-fill:#ab2328; polygon-pattern-opacity: 0;}
```

Somewhat surprised that works, since the footprint table is named `footprint_production` not `benchmarking_production`

**Comment by tomay** [comment]
Something like this works, quite repetitive (and hardcoded at the moment):

```javascript
  #benchmarking_production {polygon-fill: #CCC;polygon-opacity: 0.9;line-width: 1;line-color: #FFF;line-opacity: 0.5;polygon-pattern-file: url(https://seattle-buildings-polygon-hatch-images.s3.us-west-1.amazonaws.com/seamless_hatch_2x.png);polygon-pattern-opacity: 1;}
  #benchmarking_production [total_ghg_emissions>=1]{polygon-fill:#1f5dbe; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=2]{polygon-fill:#306fa5; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=3]{polygon-fill:#40808c; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=4]{polygon-fill:#519273; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=5]{polygon-fill:#6ba165; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=7]{polygon-fill:#90ae60; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=12]{polygon-fill:#b5bb5b; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=18]{polygon-fill:#dac857; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=24]{polygon-fill:#ffd552; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=32]{polygon-fill:#f7c34e; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=41.44444444444457]{polygon-fill:#efb24a; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=54]{polygon-fill:#e6a045; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=68]{polygon-fill:#de8f41; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=86]{polygon-fill:#d57b3c; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=112]{polygon-fill:#ca6537; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=148.16666666666697]{polygon-fill:#c04f32; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=224]{polygon-fill:#b5392d; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=378]{polygon-fill:#ab2328; polygon-pattern-opacity: 0;}

[zoom > 18] {
  #benchmarking_production {polygon-fill: #CCC;polygon-opacity: 0.9;line-width: 1;line-color: #FFF;line-opacity: 0.5;polygon-pattern-file: url(https://seattle-buildings-polygon-hatch-images.s3.us-west-1.amazonaws.com/seamless_hatch_hizoom.png);polygon-pattern-opacity: 1;}
  #benchmarking_production [total_ghg_emissions>=1]{polygon-fill:#1f5dbe; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=2]{polygon-fill:#306fa5; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=3]{polygon-fill:#40808c; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=4]{polygon-fill:#519273; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=5]{polygon-fill:#6ba165; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=7]{polygon-fill:#90ae60; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=12]{polygon-fill:#b5bb5b; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=18]{polygon-fill:#dac857; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=24]{polygon-fill:#ffd552; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=32]{polygon-fill:#f7c34e; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=41.44444444444457]{polygon-fill:#efb24a; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=54]{polygon-fill:#e6a045; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=68]{polygon-fill:#de8f41; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=86]{polygon-fill:#d57b3c; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=112]{polygon-fill:#ca6537; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=148.16666666666697]{polygon-fill:#c04f32; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=224]{polygon-fill:#b5392d; polygon-pattern-opacity: 0;}
  #benchmarking_production [total_ghg_emissions>=378]{polygon-fill:#ab2328; polygon-pattern-opacity: 0;}
}
```


That looks like this at z17: 
![image](https://github.com/user-attachments/assets/5b4b541f-c370-4059-a841-eee207195a4f)


And transitions to a wider, less dark pattern at z18:
![image](https://github.com/user-attachments/assets/0dc580e4-be5c-4f50-aec3-52e2e12e31de)

**Comment by tomay** [comment]
Okay I've prototyped a solution that does the switch at z18. 

Also worth noting that the Carto basemap drops out at z19, but the map allows zooming up to z29 (!!)

**Comment by tomay** [comment]
New idea: instead of hatch for null values, use a grey value with a darker grey outline. 

Presumably, this applies everywhere we hacked in the hatch pattern for _null_ values: 
* total_ghg_emissions "Total Seattle GHG Emissions"
* total_ghg_emissions_intensity "Seattle GHG Intensity"
* site_eui_wn "Site EUI (WN)"

There were a number of changes made to get this working in the first place, see: 
https://github.com/GreenInfo-Network/seattle-building-dashboard/issues/74#issuecomment-1786211433

- [ ] Revert changes to `seattle.json`, or at least rename the field named `hatch_null_css`, which we added specifically and only for the conditional hatch pattern
- [ ] Probably we could have a regular condition in `cartoCss` that handles `null` values, since we no longer need the rules for `polygon-pattern-file` and `polygon-pattern-opacity`? That would be particularly handy, as it wouldn't be dependent on the incoming field whatsoever, as the hatch currently is. 
- [ ] Revert the more recent changes to the generation of `cartoCss` where we handled zoom dependency for the hatch fill
- [ ] Consider deleting the S3 bucket once the dust settles on this

**Comment by tomay** [comment]
Unfortunately, no we can't just have a color for `null` that applies equally to all, because of the request to **also** have a special outline for these.  That means these are truly unlike the others, and we have to employ special hacks for them, similar to how we setup the hatch pattern .

**Comment by tomay** [comment]
Shaping up like so: 

![image](https://github.com/user-attachments/assets/0ee01202-37d3-4a5c-b4f9-e9ede0c133c1)

**Comment by tomay** [comment]
This one is a bit of a mystery: 

![image](https://github.com/user-attachments/assets/bfe7720c-4cc4-4b03-bfd4-4e12f1073aed)

But it can't be selected, and it's really not present in the footprints

I believe this is the outdoor water area at the Science Center, not a footprint at all despite superficially looking like one

![image](https://github.com/user-attachments/assets/76a0b2e0-4991-4740-9dd5-40d8abf191ef)

**Comment by danrademacher** [comment]
Mike OKed this during call on 9/16
