### ISSUE TITLE
error with "HARVARD MARKET (QFC Portion)"

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#12]
This one doesn't render at all: 

http://localhost:8080/#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61425&lng=-122.32243&zoom=16&building=867&report_active=true

Not clear why, it's got a row for "2020" and has an `eui_wn`. Looks like an error with one of the existing charts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201499885939465)

**Comment by tomay** [comment]
Okay, this one doesn't work currently, so perhaps not our problem:

https://www.seattle.gov/energybenchmarkingmap/#seattle/2019?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61976&lng=-122.32139&zoom=14&building=867&report_active=true

**Comment by tomay** [comment]
Here's another one, same error in the console: 

https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.62057&lng=-122.33390&zoom=15&building=21741&report_active=true

But this works on current production site (2019): 
https://www.seattle.gov/energybenchmarkingmap/#seattle/2019?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.62595&lng=-122.33392&zoom=14&building=21741&report_active=true

**Comment by tomay** [comment]
That second error is MIRABELLA RETIREMENT COMMUNITY

**Comment by tomay** [comment]
And sure enough, previous (2019) data has property type....

![image](https://user-images.githubusercontent.com/740512/146288213-c8eb3f54-f624-4dba-97ab-c4dc47cb63be.png)

**Comment by danrademacher** [comment]
I filed this for Terry over in #19 and he said he would back fill. Closing this one as a dupe
