### ISSUE TITLE
handling nodata with iscompliantflag

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#122]
When they eventually get us new data, it will include a new field, `iscompliantflag` with `Y` or `N` (or `y` or `n`, we shall see).

Set these to null if iscompliantflag is N
* Total Seattle GHG emissions
* GHG Intensity
* Site EUI WN
* Energy Star Score

This really should happen in R, but that's not happening, so we should just make an SQL query that does this, and we have to remember to run it when the data gets updated.

We should also add a note to the data update documentation on Sharepoint that includes this requirement and the relevant SQL statement they need to tun.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208383844407059)

**Comment by tomay** [comment]
As much as I don't like the idea of having to remember to run a SQL update on CARTO every time we update data (seems way too easy to forget that step), I don't see a clear way to handle this on the frontend, yet. 

It's not a typical map where we have a full set of data on board, if there was, we could iterate and update in place. Instead, the data largely stays as-is remotely in CARTO, and there is code to generate CartoCSS to visualize it based on rules for a single field. 

To further complicate this, there is currently no selection for NULL on the field in question. Instead, there is a baseCartoCSS that defines the base case, that acts as a fallback if other CSS rules don't match.  This is how we get `#CCCCCC` for buildings with null values.  

I'm not even sure you can select for NULL in CartoCSS? And can you mix and match fields in rules? 

This is how the constructed CartoCSS looks presently:
```javascript
#benchmarking_production {polygon-fill: #CCC;polygon-opacity: 0.9;line-width: 2;line-color: #636363;line-opacity: 0.5;}
#benchmarking_production [total_ghg_emissions>=0]{polygon-fill:#1f5dbe; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=2]{polygon-fill:#306fa5; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=2]{polygon-fill:#40808c; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=3]{polygon-fill:#519273; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=4]{polygon-fill:#6ba165; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=5]{polygon-fill:#90ae60; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=7]{polygon-fill:#b5bb5b; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=11]{polygon-fill:#dac857; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=17]{polygon-fill:#ffd552; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=25]{polygon-fill:#f7c34e; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=35]{polygon-fill:#efb24a; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=48]{polygon-fill:#e6a045; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=62]{polygon-fill:#de8f41; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=81]{polygon-fill:#d57b3c; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=106]{polygon-fill:#ca6537; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=145]{polygon-fill:#c04f32; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=223.8888888888887]{polygon-fill:#b5392d; line-color: #FFF}
#benchmarking_production [total_ghg_emissions>=368.6666666666665]{polygon-fill:#ab2328; line-color: #FFF}
```

Can we add a rule to this that looks up values in more than one field? Can we compare against NULL?

Something like: 

```javascript
#benchmarking_production [total_ghg_emissions>=0 && site_eui_wn = NULL]{polygon-fill:#CCC; line-color: #636363}
```

**Comment by tomay** [comment]
[Found a place in code we could do this](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/app/collections/city_buildings.js#L165-L175), which I'd forgotten about

Looks like at one time we were doing a trim on `property_type` there, which we successfully lobbied to have included in R

But we could use this as a hook to transform data with conditionals, e.g. to set `ghg_emissions` to null if `site_eui_wn` is null

Which is bound to be less complicated than trying to hack in something using CartoCSS

**Comment by tomay** [comment]
Ack, that doesn't help: The data on CARTO remains the same, and that's where this gets evaluated. 

So yes, the options are to run a custom SQL command each and every time we update the data, or to continue looking into some convoluted CartoCSS hack that may work or more likely isn't supported.

**Comment by tomay** [comment]
Some CartoCSS documentation:
* https://github.com/mapbox/mapbox-studio-classic/blob/mb-pages/docs/studio-classic-manual/04-classic-manual-cartocss.md
* https://tilemill-project.github.io/tilemill/docs/manual/carto/

**Comment by tomay** [comment]
Couple of updates
1. We should do the in memory update in `collections/city_buildings.js`, to hopefully help with the historgram representations
2. The following CartoCSS seems to be working to trap nulls across fields: 
```javascript
#benchmarking_production [total_ghg_emissions>=0][site_eui_wn=null]{polygon-fill:#CCC; line-color: #636363}
```

Here is a comparison 

### localhost with this in place:
<img width="835" alt="image" src="https://github.com/user-attachments/assets/13fbef5b-b62f-42dd-a8c1-6ba4761279c5">


### staging (no such fix):

<img width="828" alt="image" src="https://github.com/user-attachments/assets/9bf838e3-c6b9-4a2b-868a-fc01fd84e4cc">


One thing that's interesting is how many buildings change, and how many of them are not "blue" in the first place. 

It seems correct, from staging again: 

![image](https://github.com/user-attachments/assets/d90e5b2f-3219-4d90-a431-719dc075cbbf)

![image](https://github.com/user-attachments/assets/9a098c43-a919-41da-b54c-d448ef386681)

**Comment by tomay** [comment]
This seems to be working and I've pushed it to staging. 

A few things to note: 
- "fixing" the map and histograms requires what feel like data hacks in several places: 
    - For the historgrams, we have to iterate all data rows when the app loads to set GHGs and Energy Star to `null` if EUI is `null`
    - Map tiles are generated from data on CARTO, where we haven't changed the data, so we also have to employ CartoCSS hacks to symbolize `null`, if EUI is `null` 
    - None of this makes use of the forthcoming `isCompliantFlag`, which as I understand is just a "Y/N" based on `null` EUI. Right now we just test for null `site_eui_wn` which seems more straightforward
    - If instead we need to use `isCompliantFlag`, then that's relatively easy to change in two places

This all works, but to me it highlights the fact that the data should be changed in the R script before any of the data reaches CARTO or the map application

Also may be worth mentioning that data downloads will not reflect what is shown on the map (map shows `null`, data shows value).

**Comment by tomay** [comment]
Now that we have the historic 2015-2023 data, returning to this last item:
> If instead we need to use isCompliantFlag, then that's relatively easy to change in two places

there is an `iscompliantflag` but it's inconsistently applied. 

This query
```sql
SELECT year, iscompliantflag FROM public.carto_2015_2023_data_extra_filtered group by year, iscompliantflag order by year
```

Shows that most years include `true`, `false` and `null`. We could test for `iscomplliantflag === "true"`, or we could leave it alone and maintain it as described above (testing for null `site_eui_wn`)

**Comment by tomay** [comment]
Trying to replace `site_eui_wn` tests with `iscompliantflag`, but getting an error from CARTO: 

```json
    {
        "type": "layer",
        "message": "Postgis Plugin: ERROR:  column \"iscompliantflag\" does not exist\nLINE 1: ...e_geom_webmercator\",1e-05),1e-05,true),5) AS geom,\"iscomplia...\n                                                             ^\nin executeQuery Full sql was: 'SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints(\"the_geom_webmercator\",1e-05),1e-05,true),5) AS geom,\"iscompliantflag\",\"total_ghg_emissions\" FROM (SELECT a.*,b.total_ghg_emissions,b.total_ghg_emissions_intensity,b.site_eui_wn,b.energy_star_score,b.neighborhood,b.councildistrict,b.propertygfabuildings,b.yearbuilt,b.id FROM footprints_production a,carto_2015_2023_data_extra_filtered b WHERE a.buildingid = b.id AND b.year=2023) as cdbq WHERE \"the_geom_webmercator\" && ST_SetSRID('BOX3D(-20037508.3 20037508.25881302,-20037508.25881302 20037508.3)'::box3d, 3857)'\n",
        "subtype": "query",
        "layer": {
            "id": "layer0",
            "index": 0,
            "type": "mapnik"
        }
    }
```

**Comment by tomay** [comment]
Seems like we'll be going deeper down a rabbit hole to get `isCompliantFlag` to work:

Adding `[iscompliantflag=false]` to the derived CartoCSS is identical to how we were testing for `[site_eui_wn=null`] and to do that we add a single rule: 

```css
#carto_2015_2023_data_extra_filtered [total_ghg_emissions>=0][iscompliantflag=false]{polygon-fill:#CCC; line-color: ...
```
The key part is 
`[iscompliantflag=false]`

Previously this was 
`[site_eui_wn=null]`

Seems straightforward enough, but unfortunately, as part of this, the code also generates SQL to join footprints onto buildings. [That happens here in building_layer.js](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/app/views/map/building_layer.js#L241-L255)

I'm not sure I entirely understand how the CartoCSS relates to the SQL, but that sql ends up looking something like this when we inject that `iscompliantflag` into the CartoCSS:
```sql
(SELECT a.*,b.total_ghg_emissions,b.total_ghg_emissions_intensity,b.site_eui_wn,b.energy_star_score,b.neighborhood,b.councildistrict,b.propertygfabuildings,b.yearbuilt,b.id FROM footprints_production a,carto_2015_2023_data_extra_filtered b WHERE a.buildingid = b.id AND b.year=2023)
```

That ends up as a subquery posted to CARTO, as seen in the previous comment, and this is where CARTO errors out with `column \"iscompliantflag\" does not exist`

The issue is that isCompliantFlag does not exist in `('city').get('map_layers')` [aka `map_layers` on `seattle.json`]. 

The reason it worked before is that `site_eui_wn` _does_ already exist in `seattle.json` `map_layers`, and granted, this was a bit lucky. Here's what that looks like, an nested object within `map_layers`: 
```json
        {
            "title": "Site EUI (WN)",
            "field_name": "site_eui_wn",
            "display_type": "range",
            "range_slice_count": 18,
            "section": "Energy Performance Metrics",
            "color_range": ["#1f5dbe","#599b67","#ffd552","#da863f","#ab2328"],
            "null_outline_css": true,
            "unit": "kBtu",
            "formatter": "fixed-1",
            "filter_range": {"min": 0, "max": 1500},
            "description": "Weather-normalized site energy use is the total amount of all the energy a property consumes on-site annually, as reported on utility bills. Site energy use is measured in thousands of British thermal units (kBtu)."
        },
```

Options: 
1. We could add a fake entry to `map_layers` for `isCompliantFlag`, and everything should just work with the footprints. BUT, I have no idea what the side effects are, or how else these keys are used, where or for what purpose. 
2. We could hack in an entry for `iscompliantflag` so that it's always in that subquery. But that just seems like a bad idea, as a way to force this to work, for this one arbitrary field that we just arbitrarily added.
3. We could just continue to use `site_eui_wn` directly, since as I undertsand it, `isCompliantFlag=false` is the equivalent of `site_eui_wn=null`

**Comment by tomay** [comment]
Going with option 2 above.

**Comment by tomay** [comment]
But wait, here's an example of a building that has a `site_eui_wn`, but isCompliantFlag is `False`

![Image](https://github.com/user-attachments/assets/92cd1295-51f1-4a6c-85dd-ff9f4f0df198)

https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2023?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61369&lng=-122.34022&zoom=17&building=20071

So I think I need guidance here.
* Is this expected? 
* Should we override the `site_eui_wn` in some way, and show the "Incomplete Data" message?
* Related to the above, should we still be overwriting these "related" fields (total_ghg_emissions, total_ghg_emissions_intensity, energy_star_score) when we have `isCompliantFlag` false? [See here](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/app/collections/city_buildings.js#L171-L178).

**Comment by tomay** [comment]
Answers: 
1. It is expected to have `isCompliantFlag=false` and a positive `site_eui_wn` 
2. Keep drawing the footprints/circles according to `isCompliantFlag` and the popup message of "Incomplete Data" based on `site_eui_wn`
3. Yes, for now, keep overwriting those fields as we are

**Comment by tomay** [comment]
Seems like this is still generating some confusion: 

> One thing I just noticed in the test environment is that there are a handful of buildings in the GHG Emissions/GHGI maps displaying as grey with the outline (indicating incomplete data), but they display a valid EUI when I click on them and when I switch to the EUI layer.

> Can you see if you can fix this? If a property has a valid EUI, it should be able to calculate GHG emissions/GHGI.

 > These properties are 320, 868, and 174.

My reply: 

> Those three buildings all have isCompliantFlag = FALSE for the most recent years, which is the only attribute I'm using to draw the grey footprints for the GHG and Energy Star Score layers. This is a change we just made a few weeks ago with the release of the new schema. 

> Let me know if that should somehow be displayed differently, but sounds like it could be a data issue with these specific properties?

**Comment by tomay** [comment]
These three buildings were fixed upstream to make `isCompliantFlag = TRUE`
