### ISSUE TITLE
Final pass on how-to documentation

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#136]
This is to complete Task 3.5, Provide Written Guidance for Map Updates

* Review and update tutorial instructions – alongside the tutorial updates, but we're not trying to make this a non-dev task
* Update field names to match latest changes in existing documentation

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208941510204264)

**Comment by danrademacher** [comment]
On Sharepoint, the documentaiton is here:
https://seattlegov.sharepoint.com/sites/OSE-External/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FOSE%2DExternal%2FShared%20Documents%2FBenchmarking%2FGreenInfo%20OSE%202024%2FGreenInfo%202024%20Deliverables%2FTask%203%2E5%20documentation&viewid=35dba9c9%2Dc2c7%2D47c7%2Db35d%2D310aed53921c

And because there's a 90% chance that link will fail, here's the visual filepath:
![Image](https://github.com/user-attachments/assets/db5870fc-3832-4f7b-9cde-06853945a375)

**Comment by danrademacher** [comment]
Once Tom finishes final pass on Drive, we need to upload these to Sharepoint, whichever one of us has time and can get into the system!

**Comment by tomay** [comment]
I made updates to the files we have saved here: 
https://drive.google.com/drive/folders/1UncS-nkkfGcON7an59a6tsS0IZOoHeSJ

And then uploaded them to Sharepoint, using the link Mike shared with us today:

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/6ce52c94-8b3d-43be-affc-6685945f8852" />

I did not touch the "footprints" documentation. It looks like the file on Sharepoint is newer than our copy on Drive. 

Closing this assuming we are done for now
