### ISSUE TITLE
Building details card collisions

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#14]
Longer GHG gas readings lead to the following: 

![image](https://user-images.githubusercontent.com/740512/145619366-627f4e15-2cde-47d4-bb72-905ad1745110.png)

Card style like this could help? 

```css
    position: relative;
    font-size: 16px;
    min-width: 251px;
    width: auto;
    height: 100%;
    border: 2px solid #003DA5;
    border-radius: 10px;
    margin-right: 20px;
    padding: 14px 42px 0px 16px;
```

![image](https://user-images.githubusercontent.com/740512/145619782-fed94b33-5b0b-45e1-839a-afd953773a82.png)

Needs more testing

Maybe we need to bring the measure below where it can collide with the corner icon?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201500373367358)

**Comment by tomay** [comment]
Current approach: 

![image](https://user-images.githubusercontent.com/740512/145909943-4ec39d35-68d2-4e2a-998b-4b1c5130fce4.png)

Differs somewhat from the design, but this will allow even longer numbers

![image](https://user-images.githubusercontent.com/740512/145909868-1527e0b1-d4e4-409b-9ee3-b4bc400364a3.png)

**Comment by danrademacher** [comment]
- [ ] Left align the lower arrow text to text above
- [ ] Move icon to lower right corner
- [ ] Balance vertical white space above and below

**Comment by danrademacher** [comment]
Looking good:
![image](https://user-images.githubusercontent.com/1423200/146429476-166f8e60-5c7f-4320-b5c4-b2f57ff72f06.png)
