### ISSUE TITLE
Tutorial updates

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#143]
### Edits to existing steps

- [x] Step 3

> This looks like an image superimposed on the screen… can you make this actually a functional dropdown? Also, the text displayed for the dropdown is different than what is currently there. (“All Building Types”)

> Can you also use the phrase “building type” in the text description rather than “property type”

** This is an image, it was the only way I could make this work. I was unable to make the synthetic dropdown ("Selectize") open/activate in the tutorial context. 

- [x] Step 8

> Change “performance profile” to “performance report” in the text box.

> This isn’t exactly a tutorial modification but can we also change the “View Building Report” button in the pop-up to say “View Performance Report”? If so, we would also need to update the last few words of the text box.

See #142 for the button change

### New Report Steps replacing existing report steps

- [x] Step 10 - New

New, open report for CITY HALL, and focus on this box on the report: 

![Image](https://github.com/user-attachments/assets/b7b772c3-2945-443c-8f08-37e482faf5a5)

Text: 
> BUILDING PERFORMANCE DETAILS
This customized Performance Report displays the building’s Site EUI and GHG Intensity for the selected reporting year, as well as other useful benchmarking information.

- [x] Step 11 - New

Focus on this element: 

![Image](https://github.com/user-attachments/assets/380e73f8-39ad-4b67-a104-76c5e3078234)

Text: 
> ENERGY AND EMISSIONS
The report displays how property energy consumption translates to Greenhouse Gas emissions.

- [x] Step 12 - New

Click second tab "Emission Targets", focus on this element: 

![Image](https://github.com/user-attachments/assets/e32dd99b-6329-4ef4-80a0-d7c0acf6d8c7)

Text: 
> EMISSIONS TARGETS
The report displays a building’s estimated emissions targets under the Seattle Building Emissions Performance Standard law, as well as its current GHG intensity.

- [ ] Step 13 - New

Click third tab "Energy Targets", focus on this element: 

![Image](https://github.com/user-attachments/assets/d11d95cc-cd96-42ff-b251-556db37bd216)

Text: 
> ENERGY TARGETS
If applicable, the report also displays a building’s estimated EUI target under the Washington state Clean Building Performance Standard law.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208992831611331)

**Comment by tomay** [comment]
Notes: 
1. Yes, the dropdown is an image, I was unable to interact with the dropdown directly in the tutorial context
2. STEP 11: There no container that directly matches the focus target, I found the next closest
3. STEP 12: There is no container that can focus on both of these charts, they are conditional and can't be wrapped. Given that, should we drop this part of the sentence "as well as its current GHG intensity." At the moment I have added an additional step

**Comment by tomay** [comment]
- [ ] Landing page: Change “for buildings 20,000 square feet and larger” to “for buildings larger than 20,000 square feet”
- [ ] Step 10Update the Seattle Open Data Portal link to [https://data.seattle.gov/browse?q=building+energy+benchmarking&sortBy=newest&utf8=%E2%9C%93&pageSize=20](https://data.seattle.gov/browse?q=building+energy+benchmarking&sortBy=newest&utf8=%E2%9C%93&pageSize=20)
- [ ] Between step 9 and step 10, there’s a half second before the step 10 box appears, where the shading completely goes away and it almost looks like the tutorial has stopped. I think the delay would be fine if the shading stayed up on the screen, to emphasize there’s nothing yet highlighted. (See attached video) 
- [ ] Step 13: Update text to “The report also displays whether or not a building is currently on track to meet their first GHG intensity target.”
- [ ] Step 14: Displaying the incorrect text. Should be: “The report displays a building’s estimated emissions targets under the Seattle Building Emissions Performance Standard (BEPS) law.”

But the accompanying screenshot shows Step 12:
<img width="731" alt="Image" src="https://github.com/user-attachments/assets/c7cfe995-95c3-43fa-901b-8b547cd61128" />

**Comment by danrademacher** [comment]
Complete and approved by client
