### ISSUE TITLE
Calculation Error in energy use trends % change?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#16]
Pulled out of #9 

I think they are calculating percent change wrong here: 

![image](https://user-images.githubusercontent.com/740512/145898589-01820f8b-3b78-45a8-beaf-7242501d714d.png)

```javascript
    const previousValue = yearData[0].val;
    const selectedValue = yearData[1].val;
    return ((selectedValue - previousValue) / selectedValue) * 100;
```

They are dividing the difference by the current value, not the initial value

The formula should be:
`( current_value - initial_value ) / initial_value * 100`

Simple real-life example from last comment

`(3-2)/3 = 33%`
vs
`(3-2)/2=50%`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201523156706046)

**Comment by danrademacher** [comment]
@seattle-benchmarking can you take a lok at this issue and see if you agree we should change this calculation? It would change some outputs even for the same data compared to the current produciton deploy, so we wanted to check with you before making a change.

**Comment by seattle-benchmarking** [comment]
@danrademacher yes you're right. it should be using the initial value as the denominator. Thanks for catching this.
