### ISSUE TITLE
Basic PDF layout issues

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#17]
Setting aside the edge-case bugs we're tracking in #15 , we have a few hopefully more straightforward issues with the size and layout of things in the PDF:

1. Header boxes overflow
![image](https://user-images.githubusercontent.com/1423200/146073126-6acba932-890c-49b0-8328-b1f6aa14e10e.png)
1. CBPS date boxes too big and crowded
![image](https://user-images.githubusercontent.com/1423200/146279190-c9879160-19a5-4c41-a51f-565ef08660f8.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201523597063610)

**Comment by tomay** [comment]
very weird that some buildings print three links in the footer: 

![image](https://user-images.githubusercontent.com/740512/146462984-33ddb377-195d-41b8-b15d-d51065f3a140.png)

and some only two (which matches the website afaik):

![image](https://user-images.githubusercontent.com/740512/146463024-e62dcf51-e6b9-4095-8fe3-b34dfacac216.png)

Unless there is some building-specific switch here that I missed until now?

**Comment by tomay** [comment]
okay, with media queries, I can get the 3 link case buttons to not overflow:

![image](https://user-images.githubusercontent.com/740512/146466849-14610399-4b32-42c5-b603-14ffe26b4818.png)

**Comment by tomay** [comment]
Done in 53c65bd but not tagged in a commit

**Comment by tomay** [comment]
Closing for now. Anything more specific should get a new issue
