### ISSUE TITLE
Buildings with missing TYPE

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#19]
Confirmed with Terry  that all buildings should have a TYPE, but in the past maybe he backfilled where that was missing from the city's data. It is causing errors in calculations that compare a building to similar buildings.

Terry will populate.

There are 515 records like that. Since empty strings are not `null` in Postgres, I used this query to find those:

```sql
SELECT count(*) FROM public.seattle_buildings_master_copy_for_update2020 where length(property_type)=0
```

Those records are just 107 buildings across multiple years:

```sql
SELECT count(distinct(id)) FROM public.seattle_buildings_master_copy_for_update2020 where length(property_type)=0
```

And those buildings are:

```
id
84
85
100
107
278
468
473
484
642
19472
19550
19559
20145
20209
20377
20393
20402
20432
20815
20885
20970
21114
21244
21344
21442
21471
21568
21594
21665
21741
21862
22060
22252
22371
22830
22955
22956
22961
23025
23056
23231
23454
23531
23682
23701
23708
23960
24170
24458
24700
24746
24769
24782
24888
24958
25025
25259
25490
25737
25772
25856
25965
26157
26236
26249
26289
26324
26400
26402
26429
26550
26730
26741
26839
26989
27071
27397
27682
27977
29069
49695
49829
49945
49987
50063
50085
50167
50179
50265
50327
50330
50332
50463
50505
50511
50529
50532
50542
50543
50549
50661
50663
50664
50674
50679
50681
50682
```

cc @@seattle-benchmarking

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201528601002504)

**Comment by seattle-benchmarking** [comment]
![image](https://user-images.githubusercontent.com/58457382/146608436-b3bf51d8-ad5d-4692-acd5-75de8e8a03db.png)

buildings with N/A in type won't display the report at all. use this id to test fix

**Comment by danrademacher** [comment]
Terry, can you clarify the note about `24888`? Our understanding is that you will be populating these `property_type` fields and we can assume it won't be null.

Right now, `24888` is now a Senior Center Community, so it _mostly_ works. But this one still fails with the NA:
https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61779&lng=-122.33233&zoom=14&building=21471

There are still 22 buildings with no `property_type` with this query in CARTO:
```sql
SELECT distinct(id) FROM public.seattle_buildings_master_copy_for_update2020 where length(property_type)=0
```

But for `24888` and other previously null buildings, we're also seeing missing data for the Building Type EUI_wn, which is causing the infinity symbol in this screenshot:
![image](https://user-images.githubusercontent.com/1423200/147004856-3d68f7e9-83da-46e8-b401-43b07653bd48.png)

It looks like there are 147 buildings that have some value for `property_type` but nothing for `building_type_eui_wn`. That's in this query:
```sql
SELECT count(distinct(id)) FROM public.seattle_buildings_master_copy_for_update2020 where length(property_type)>0 and building_type_eui_wn is null
```

**Comment by seattle-benchmarking** [comment]
@danrademacher sorry that note above (on id = 24888) was a note to myself. I was working through these today but hadn't finished. There are multiple different data issues causing problems with this. I'll follow up tonight once I finish cleaning up what I can.

**Comment by seattle-benchmarking** [comment]
@danrademacher I fixed the data issues for `building_type_eui_wn` for Senior Center Community
That fixed the infinity sign issue
But not seeing the Energy Use Compared to Average chart for a few Senior Center Community buildings
id = [21741](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?categories[0][field]=property_type&categories[0][other]=false&categories[0][values][]=Senior+Care+Community&layer=energy_star_score&metrics[]=energy_star_score&sort=energy_star_score&order=desc&lat=47.61946&lng=-122.32549&zoom=16&building=21741&report_active=true)

**Comment by seattle-benchmarking** [comment]
okay i figured that out but it's related to something else. will close this out and open a different issue
