### ISSUE TITLE
Emissions per square foot card - pulling wrong data field for kg/sf

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#22]
The second building details card (emissions per square foot) is using the wrong data field. Should be pulling from total_ghg_emissions_intensity instead of total_ghg_emissions. 
e.g. [this building](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61147&lng=-122.33002&zoom=15&building=659&report_active=true) should be showing 0.3 kg/sf instead of 385.6

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201530325067624)

**Comment by seattle-benchmarking** [comment]
in SQL 
SELECT id, year, total_ghg_emissions, total_ghg_emissions_intensity FROM public.seattle_buildings_master_copy_for_update2020
where id = 659 and year = 2020

**Comment by tomay** [comment]
After updating: 

![image](https://user-images.githubusercontent.com/740512/146821212-2462c3fa-98b3-4858-9e17-17c3e3b393c0.png)
