### ISSUE TITLE
Emissions per square foot card - reference to type average needs updating too

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#23]
The percent higher/lower than similar buildings reference in the emissions per square foot building details card will need updating as well. See previous (current production) version of the FUEL USE AND EMISSIONS section bubble chart for the two references. 
![image](https://user-images.githubusercontent.com/58457382/146490371-ed123e39-b61d-4269-b55e-21bac1686d2e.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201530335036686)

**Comment by tomay** [comment]
I've updated the method that generates average values to also use `total_ghg_emissions_intensity`

For the Russel Investments Center, I get a mean value of `0.63076`, slightly different from what shows above, but this is 2020 data, so a difference could be expected. 

I notice that the existing method filters out buildings with null `site_eui` before calculating the mean. Should this be filtering on `site_eui_wn` instead or is there no difference?

**Comment by seattle-benchmarking** [comment]
@tomay thanks. yes it should be updated so using site_eui_wn to calculate the mean
