### ISSUE TITLE
Issue displaying Supermarket / Grocery Store building reports

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#25]
I tried opening 5 or 6 Supermarket / Grocery Store building reports and all showed this:
![image](https://user-images.githubusercontent.com/58457382/146607441-fbc12ef8-71e0-423f-8883-93852f96c06a.png)

see examples: id = 464, 25914, or 802

seems similar to the issue you saw with Harvard Market

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201534374674197)

**Comment by tomay** [comment]
Looks like the 2020 data has both `Supermarket / Grocery` and `Supermarket / Grocery Store`. 

Then the thresholds defined in `seattle.json` includes only `Supermarket / Grocery`

From that it looks like the way forward is to change all `Supermarket / Grocery` to `Supermarket / Grocery Store` in the 2020 data and update `seattle.json` to match. 

But this may also depend on how this type is coded in previous years. I see that 2019 has `Supermarket / Grocery Store`, but I haven't checked years prior to that.

**Comment by seattle-benchmarking** [comment]
@tomay I updated the data so it's consistently 'Supermarket / Grocery' now since that's more concise. The reports now display but there are other issues. The main map expects 'Supermarket / Grocery Store' in the filter. And the emissions intensity card reference might need updating: 
![image](https://user-images.githubusercontent.com/58457382/146871583-f635a292-562a-4202-8c13-4c0b99fab9ab.png)

Same with the ENERGY USE COMPARED TO AVERAGE chart

**Comment by tomay** [comment]
I believe these issues are resolved now after a fresh deploy. If not, let me know

**Comment by seattle-benchmarking** [comment]
> I tried opening 5 or 6 Supermarket / Grocery Store building reports and all showed this: ![image](https://user-images.githubusercontent.com/58457382/146607441-fbc12ef8-71e0-423f-8883-93852f96c06a.png)
> 
> see examples: id = 464, 25914, or 802
> 
> seems similar to the issue you saw with Harvard Market
> 
> ┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201534374674197)

This original issue was showing up with a few other types - but was because a bunch of the data had returns/spaces after the text. Should all be cleaned up now.

And the filter and emissions intensity data looks good too.
