### ISSUE TITLE
Awkward return on longer property_type strings

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#26]
Return creates problems on longer strings for the property_type variable in the header. 

![image](https://user-images.githubusercontent.com/58457382/146607701-99e4ed44-ede0-4b65-94cc-13bd64858075.png)

![image](https://user-images.githubusercontent.com/58457382/146607688-c9b1b156-d0fa-4a5b-b401-350255489470.png)

types include at least: 

* Residence Hall / Dormitory
* Small- and Mid-Sized Office
* Refrigerated Warehouse
* (probably) Supermarket / Grocery Store

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201534380347143)

**Comment by tomay** [comment]
This is working again on the longest possible type

![image](https://user-images.githubusercontent.com/740512/146825185-2acc026a-e0be-4693-8bf1-91502a295f97.png)

Very large values in the cards to the right could still cause collision, but will need a closer look at the data to know if that's a real concern or not

![image](https://user-images.githubusercontent.com/740512/146825522-266bf7eb-689f-4eca-9f7d-67cc297f5af2.png)
