### ISSUE TITLE
Energy Use Trends - Overlap in Data Labels

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#27]
Seeing a lot of overlap in data labels on the line chart. Since this is likely an inherited issue I'll tag as nice to have.
example - id = 24598
![image](https://user-images.githubusercontent.com/58457382/146608587-e6d0a164-ac96-44bb-8b56-a7f05a8b59d2.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201534494957571)

**Comment by tomay** [comment]
I've got an attempted fix in place. It looks pretty good on the example provided, and I've checked 10 or so additional buildings - all look good, but some additional testing would be helpful.

**Comment by seattle-benchmarking** [comment]
Will test today

**Comment by seattle-benchmarking** [comment]
This seems to be performing pretty well - thanks!
