### ISSUE TITLE
id = 25354 not displaying Energy Use Compared to Average

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#32]
Energy use compared to average not displaying for ID = 25354

I have not been able to replicate this behavior with other similar buildings but same thing happened for 2019 report for this building. The current [production build](http://www.seattle.gov/energybenchmarkingmap/#seattle/2019?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.62150&lng=-122.34263&zoom=14&building=25354&report_active=true) shows the graph for this building. 

https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?categories[0][field]=property_type&categories[0][other]=false&categories[0][values][]=High-Rise+Multifamily&layer=energy_star_score&metrics[]=energy_star_score&sort=energy_star_score&order=desc&lat=47.61155&lng=-122.34263&zoom=16&building=25354&report_active=true

![image](https://user-images.githubusercontent.com/58457382/146876280-0615ea4e-31af-4dbd-97c4-36291aba900e.png)

**Comment by tomay** [comment]
Turns out it is failing in this chart, related to the work yesterday to tweak label positions

The data point for 2017 is not showing for some reason

![image](https://user-images.githubusercontent.com/740512/146975455-37474953-256d-46ef-b68e-a9d662a7cfac.png)

**Comment by tomay** [comment]
Turns out there is no `site_eui_win` for 2017 which throws off the approach for detecting label collision between pairs of labels in different series. For now, I just skip collision detection if the two series are not equal length
