### ISSUE TITLE
links can overlap footer in PDF

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#36]
Example is 50530

![image](https://user-images.githubusercontent.com/740512/147295372-9817796d-93ba-4a87-96fc-b0fa1734a2e3.png)

One solution could be to force the links to the third page always

[50530.pdf](https://github.com/GreenInfo-Network/seattle-building-dashboard/files/7771620/50530.pdf)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201588895774966)

**Comment by danrademacher** [comment]
This is likely resolved by changes requested in #38

**Comment by danrademacher** [comment]
No longer an issue since Stamen replaced the whole building report
