### ISSUE TITLE
issue with long building names in pdf 

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#37]
see id=315 from the testing sample
![image](https://user-images.githubusercontent.com/58457382/147691852-b24c776f-e959-4f96-90d4-4f744b3dad28.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201571257100843)

**Comment by danrademacher** [comment]
Looks like we can fix this with a bump up in height on the title area in print.css. Here's the longest name in the system:
![image](https://user-images.githubusercontent.com/1423200/147693650-8301cfcf-e608-4fe8-942a-0215e132619b.png)

that's `building=730`

And confirming with shortest as well:
![image](https://user-images.githubusercontent.com/1423200/147693750-4c5315ab-c8e6-447e-9148-c0981327d639.png)
