### ISSUE TITLE
explore ability to limit pdf to 2 pages

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#38]
the pdf reports with a cbps flag are running over to a third page. 

can you look into cutting out most of the Find Ways to Save and shrinking components on the second page slightly to fit:
![image](https://user-images.githubusercontent.com/58457382/147692069-b4ba7229-12d3-42e3-9846-b5768e112fd4.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201593259299161)

The top two sections on page 2 (Energy Use vs Avg and Trends) are already pretty compressed. But seems like the Performance Standard section could be slightly shorter vertically to find the button links.

**Comment by danrademacher** [comment]
@seattle-benchmarking here are samples with changes to get to 2 pages with the full CBPS info:
[730-2pages.pdf](https://github.com/GreenInfo-Network/seattle-building-dashboard/files/7790331/730-2pages.pdf)

Note that these would apply to all PDFs not just long ones. So here's an example of a shorter one:
[24886-2pages.pdf](https://github.com/GreenInfo-Network/seattle-building-dashboard/files/7790333/24886-2pages.pdf)

**Comment by danrademacher** [comment]
Reopined pneding Terry's review of those two sample PDFs

**Comment by danrademacher** [comment]
Assuming this is OK
