### ISSUE TITLE
Receive and confirm new data for fitness

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#4]
That will include:

* new boolean for show/hide Building Performance section
* new compliance date for that section
* new `eui_t`
* single `eui_wn` that will be the sole EUI reference throughout the application (currently there’s `eui` and `eui_t`)

We should both look at the data when it arrives. I can also redline the designs to match fields up on the report.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201449239379201)

**Comment by danrademacher** [comment]
Terry just emailed about the new data as follows:

> I uploaded a new table to Carto and combined it with a copy of the current production data table. See *seattle_buildings_master_copy_for_update2020*
>  
> That table includes another year of data for 2020 and adds in three new variables for your use:
> 
> - `cbps_euit` – to display in Estimated EUI Target section in two spots
> - `cbps_date` – to display in estimated compliance date section
> - `cbps_flag` – turn on or off the *Washington Clean Building Performance Standard* section
> 
> You guys can take a look and let me know if anything looks off – I imagine there will be some adjustments along the way. I added the cbps data to 2019 and 2020 but not previous years.
>  
> The other day we talked about a few things:
> 
> - You guys will calculate which buildings are 100% electric to show alternative text/images/links below the energy and emissions section – so I have not provided a variable here. You can use electricity_pct > 0.99 or something
> - We discussed changing all EUIs on the page to site_eui_wn. This means you’ll also have to use building_type_eui_wn instead of building_type_eui wherever it’s used
> - We also discussed showing NA in the cbps_date or cbps_euit ‘bubbles’ if cbps_flag was TRUE but that variable was NULL. And to have an error message to display on the chart if the cbps_euit is NULL
>   - error message: We could not estimate an EUI Target for this building with the reported data. Contact energybenchmarking@seattle.gov if you have questions.
> 
> Happy to discuss if you have questions/follow up.

**Comment by danrademacher** [comment]
Direct link to data:
https://cityenergy-seattle.carto.com/dataset/seattle_buildings_master_copy_for_update2020

I did a quick look and the table has data for
* `20916` buildings
* `1578` buildings where the Benchmark section is true

**Comment by tomay** [comment]
This may not be well understood, but it looks like I should update the table names in `src/cities/seattle.json` with this new table name (and years??)

https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json#L217-L238

**Comment by danrademacher** [comment]
Yes, that's my understanding a new`2020` element and... oh huh, every year comes from the same table but _could_ come from different tables.

I do see that all years are in this new data:
![image](https://user-images.githubusercontent.com/1423200/144922739-b8c05c7e-7a2e-48bd-be8c-fb600cd76c36.png)

So that checks out with swapping the new table name for all years and adding 2020.

**Comment by tomay** [comment]
I also added 2020's to [this section of the config](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/src/cities/seattle.json/#L370-L533), as noted in [docs/Update_data.md](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/docs/Update_data.md): 
> Under eui and each category of building, add a year entry for the latest year. 

I kept the same breaks as they had for 2019. 

Despite that, I haven't yet figured out how to get 2020 to get into the report. `this.this.scoreCardData.data` only shows 2017, 2018 and 2019 for some reason (the app itself is showing 2020 as the default year, so that's progress)

**Comment by tomay** [comment]
OK, that's fixed. I am seeing this in the 2020 data however: 

![image](https://user-images.githubusercontent.com/740512/144933453-da389afe-531f-4342-a5f1-1d032137a801.png)


2019 for comparison: 

![image](https://user-images.githubusercontent.com/740512/144933319-6ef962b9-c071-434a-8ce0-aa2dbd12694d.png)


I wonder if that's got something to do with this from Update_data.md

> In the uploaded dataset, make everything that should be numeric is numeric. Look at the master dataset and if any columns are text but should be numeric, update them::

**Comment by tomay** [comment]
The column types look correct over in Carto. I don't know what changed in the new data to suddenly make this an issue. 

For now, I made the following change in `src/app/templates/map/building_info.html`: 
```html
    <!-- old -->
    <td style="color: <%= data.chart.lead.color %>;"><%= data.chart.lead.value %></td>
    
    <!-- new --> 
    <td style="color: <%= data.chart.lead.color %>;"><%= data.chart.lead.value.toLocaleString() %></td>
```

**Comment by tomay** [comment]
Question on this comment of Terry's from above: 

> This means you’ll also have to use building_type_eui_wn instead of building_type_eui wherever it’s used

_wherever it's used_: Does this mean site wide, or on the Building Scorecard only?
