### ISSUE TITLE
building footprint update 2022

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#42]
We have a list of new buildings and old deprecated buildings, and we need building footprints that match 

1. Use [overpass turbo](overpass-turbo.eu) to get the current set of building footprints. For that I used this query: 
```bash
[out:json];

area[name="Washington"]->.b;
rel(area.b)[name="Seattle"];
map_to_area -> .a;


way["building"](area.a);
out geom;

relation["building"](area.a);out;
way(r)[!"building:part"];
out geom;
```

This was a large result (~200 MB), and I wonder if there's a more direct route for such a large download, bypassing the map/website? 

2. Still within overpass, download/export as GeoJSON

3. Load into QGIS. 
This works, but it's about 200,000 features, and includes all footprints. Looking into how we can differentiate commercial buildings from the rest.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1203423628604901)

**Comment by danrademacher** [comment]
You can also hit the Overpass API directly, at http://overpass-api.de/, at CLI. You'd just have to see what sort of request payload it requires. OP Turbo is just a GUI in front of that API as far as I know.

**Comment by tomay** [comment]
I was able to match 55 of 58 building lat-lngs to the footprints from overpass. The following do not match: 

## 1. 602 E HOWELL ST (47.61784, -122.32439)

![image](https://user-images.githubusercontent.com/740512/203621824-86f53368-8e4b-4f04-98c4-311de27f17fe.png)

Here's a comparison to this block on CARTO: 

![image](https://user-images.githubusercontent.com/740512/203622956-cbf2d34a-26b8-456e-8a60-a10cd33da6c4.png)


And Google Maps/Satellite

![image](https://user-images.githubusercontent.com/740512/203622607-96c104e2-fd82-4b97-990e-ab2431b157ea.png)

![image](https://user-images.githubusercontent.com/740512/203622740-b5cba165-d1c8-4fd0-b91c-eb391e99ca55.png)

Not easy to see what's going on, but seems likely we need to grab the one footprint closest to the point

## 2. 420 BOYLSTON AVE E (47.62267, -122.32278)

![image](https://user-images.githubusercontent.com/740512/203621737-eabf2e75-1bcb-4c57-a5ca-e100116d552d.png)

Google Satellite view: 

![image](https://user-images.githubusercontent.com/740512/203626811-610030be-ae29-4694-8be2-302c17704521.png)

This looks like a new building that we will have to digitize

## 3. 1157 N 130TH ST (47.72299, -122.34293)

![image](https://user-images.githubusercontent.com/740512/203621590-0d6451bb-35b9-489f-8543-60d2ecef6aab.png)

Google Streets view: 

![image](https://user-images.githubusercontent.com/740512/203627594-1330d154-c257-465e-85cb-bf6514d514ff.png)


Google Sat view: 
![image](https://user-images.githubusercontent.com/740512/203627461-64241016-a830-4d50-9921-362cacf73203.png)

Not sure what to make of this one. There doesn't seem to be anything here. 

The lat/lng maps here: 

![image](https://user-images.githubusercontent.com/740512/203627747-47faed37-c169-4dee-bd5e-577b16243ee3.png)

Could it be the temporary fire station? 

![image](https://user-images.githubusercontent.com/740512/203627892-e4b15442-f0c6-4842-b652-a95fa92a2252.png)

**Comment by tomay** [comment]
Getting ready to merge the new 58 buildings into the existing building footprint data from Carto called "seattle_building_outlines_20181126", I'm noting a number of instances where we've found a new footprint that matches an old footprint exactly, e.g. the one here at lower right: 

## New 
![image](https://user-images.githubusercontent.com/740512/204350450-7d5a6df0-809d-4e4a-a9b1-3d9383ddf767.png)

## Old

![image](https://user-images.githubusercontent.com/740512/204350497-346a951a-d67e-4160-8fdd-5fcea7590253.png)

Seems like we'd want to delete those prior to merge, but also makes me wonder about the original process for identifying the 58 missing footprints

I think Ill go through them all and flag duplicates for discussion

**Comment by tomay** [comment]
# Buildings to remove

1. Select the following by `OSEBuildingID`: 
```sql
SELECT * FROM public.seattle_buildings_master_copy_for_update2020
where id in ('244','21417','21530','23008','23022','23418','23888','24454','25025','25092','25839','27205','50069','441','611','19845','20376','50068','50681') order by id ASC
```

2. Export as CSV, and reduce these to a single record for each row, with `id,lat,long`

id | latitude | longitude
-- | -- | --
244 | 47.60105 | -122.33518
441 | 47.62036 | -122.34588
611 | 47.59856 | -122.33379
19845 | 47.66460037 | -122.2997208
20376 | 47.57405 | -122.30301
21417 | 47.62569 | -122.33146
21530 | 47.62007385 | -122.3454149
23008 | 47.70983 | -122.31865
23022 | 47.70519257 | -122.3224258
23418 | 47.59725918 | -122.3220338
23888 | 47.57290555 | -122.3864134
24454 | 47.59191 | -122.3266
25025 | 47.5867 | -122.30519
25092 | 47.70625 | -122.3424
25839 | 47.55317 | -122.33289
27205 | 47.70614609 | -122.3612496
50068 | 47.54425 | -122.31776
50069 | 47.53161 | -122.29944
50681 | 47.66964 | -122.37918

3. In QGIS, import as X,Y data, and spatial join on `seattle_building_outlines_20181126`to identify buildings to remove

**Comment by tomay** [comment]
# Buildings needing rectification or clarification

## WEBSTER BUILDING AKA LICTON SPRINGS K-8
OSEBuildingID | Address | Latitude | Longitude
-- | -- | -- | --
50781 | 3015 NW 68TH ST | 47.67767 | -122.39631

Notes: 
There is an existing footprint here with ID 228 (Webster Building). I could delete and replace that with 50781, but it seems likely that these two records refer to the same building, and 228 is not in the list of dropped buildings. 

![image](https://user-images.githubusercontent.com/740512/204389658-b505f8f2-77fd-41df-b413-1d96495c903b.png)

## NORTHCUT LANDING
OSEBuildingID | Address | Latitude | Longitude
-- | -- | -- | --
50767 | 4915 25TH AVE NE | 47.66517 | -122.30186

Notes: 
There is an existing and identical footprint here with ID 565. It looks like these two records refer to the same building. 

![image](https://user-images.githubusercontent.com/740512/204396621-5ecffc34-40d7-48b5-900d-e9729cfd5903.png)

## KING COUNTY YOUTH SERVICES - CAMPUS

OSEBuildingID | Address | Latitude | Longitude
-- | -- | -- | --
50689 | 1211 E ALDER ST | 47.60462 | -122.31549

Notes: 
The new footprint overlaps an existing one. Could be a rebuild? Do we keep existing (old) record and footprint with building ID 187?

![image](https://user-images.githubusercontent.com/740512/204399332-5fc3b67d-fc84-428f-ae5c-965bc2e876bd.png)

## NW ENVIROSERVICE/EVERGREEN SVCS

OSEBuildingID | Address | Latitude | Longitude
-- | -- | -- | --
50761 | 1700 AIRPORT WAY S | 47.58802 | -122.32111

There is an existing and identical footprint here with ID 23867. It looks like these two records refer to the same building.

## 820 SOUTH ADAMS BUILDING

OSEBuildingID | Address | Latitude | Longitude
-- | -- | -- | --
50760 | 820 S ADAMS ST | 47.5668 | -122.32149

There is an existing and identical footprint here with ID 24132. It looks like these two records refer to the same building.

**Comment by tomay** [comment]
Testing new complete footprint dataset against the latest complete data update
- All buildings have a matching footprint
- Every footprint has a matching building, except for the following IDs, which we can probably delete:


buildingid |
-- |
-1 |
0 |

**Comment by tomay** [comment]
All updated in CARTO as a new table called `seattle_building_outlines_2021`

Here's the Licton Springs example from above, showing overlapping footprints from different years, different rows in the data: 

## 2017
![image](https://user-images.githubusercontent.com/740512/207199846-65fe7086-8749-4a2b-8952-d6cf314e1f1f.png)

## 2021
![image](https://user-images.githubusercontent.com/740512/207199902-37331311-e370-41cd-a23d-724ad280e637.png)
