### ISSUE TITLE
Delete AWS resources?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#43]
Working on 2023 hosting, I noticed $194.54 in costs for this project.

I found the following instances on EC2:
```
seattle-energy,us-west-1,i-070643b80bee3eab0,Instance,aws:cloudformation:stack-id,arn:aws:cloudformation:us-west-1:203662178823:stack/seattle-energy/b886e840-6e54-11ec-a508-068d5b51ee87
seattle-energy,us-west-1,i-070643b80bee3eab0,Instance,client,seattle-energy-2021
seattle-energy,us-west-1,i-070643b80bee3eab0,Instance,aws:cloudformation:logical-id,Ec2Instance
seattle-energy,us-west-1,i-070643b80bee3eab0,Instance,aws:cloudformation:stack-name,seattle-energy
seattle-energy,us-west-1,i-070643b80bee3eab0,Instance,Name,seattle-energy
```

I think we can delete all this stuff, right? I think it was part of the PDF generation if I recall correctly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1203430467044327)

**Comment by tomay** [comment]
I think that's right, the [pdf-generator readme](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/pdf-generator/README.md) indicates that you can run this locally, or run it as a server on AWS. It also mentions
> An S3 bucket where the generated files will be persisted

Is that one of the listed instances? Hard to tell. I'd want to make sure those files aren't still needed. I don't believe we link to them in the application (I don't see PDFs anywhere, just a print view). My recollection is that we generated these for Terry so they could be mailed to every building? Not for use in the application.

**Comment by tomay** [comment]
I think that all of this infrastructure is terminated/deleted
