### ISSUE TITLE
New report header

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#5]
Let's start with the header as easy enough to bite off, and also at the top:
![image](https://user-images.githubusercontent.com/1423200/144131797-8a6775f6-5655-4348-8ea2-c58b39f01e04.png)

https://xd.adobe.com/view/fc56a1c7-ec9e-46c9-a352-63b9f05e276a-a905/specs/

Current appearance:
![image](https://user-images.githubusercontent.com/1423200/144132276-b0260b55-8680-4776-8bf3-30af8257031a.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201449378004145)

**Comment by tomay** [comment]
Root of the template is here: 
/src/app/templates/scorecards/scorecard.html

**Comment by tomay** [comment]
But that's just the tip of the iceberg. Virtually everything seems to be injected here: 
```
  <!-- Dynamic content -->
  <div id='scorecard-content'>
    <div id='scorecard-view'></div>
  </div>
```

**Comment by tomay** [comment]
This is how it's looking at the moment:

![image](https://user-images.githubusercontent.com/740512/144948704-9cb9d205-c40a-4f92-aca0-16998d0f4264.png)

And as I paste that I see that it's missing the text. I'll add that shortly
> *All EUIs are adjusted for weather

**Comment by tomay** [comment]
## Notes/comments/questions

Copy of the latest building data exported from Carto saved here: 
https://docs.google.com/spreadsheets/d/1mShoC9Hw5jGyP6HhN0l2N8VmV1-cVy8ZeyA8yNKTV-g/edit#gid=1583635201

### Fields used from building data in the header
1. EUI stats
    - EUI total: `site_eui_wn`
    - EUI average for this building type: `building_type_eui_wn`
2. GHG stats
    - GHG total: `total_ghg_emissions`
    - GHG for this building type: `total_ghg_emissions_intensity`, calculated on the fly as the mean of this measure for all buildings of this type

### Energy Star switch? 

The original had this in the header, but I don't see anything like this in the latest design, so I've ignored it: 
```html
    <% if (ess_logo) { %>
    <div class='sc-txt blue-new small light ess-certified'><img class='ess-logo' src='images/scorecard/energy-star-logo.svg'/><span>This building is ENERGY STAR Certified</span></div>
    <% } %>
```

### City Scorecard

It looks like the system supports a City Scorecard in addition to a Building Scorecard. I haven't heard anything about this (or I don't recall!), so I'm ignoring this for now.

**Comment by tomay** [comment]
Somethings not right with the increase/decrease figures: 

![image](https://user-images.githubusercontent.com/740512/145498230-a8af807b-2248-4815-adfd-fa33c1713b64.png)

**Comment by tomay** [comment]
okay, I see the problem

Also, I should note here the process for calculating GHG comparisons
1. Get the `total_ghg_emissions` for this building
2. Get the mean of `total_ghg_emissions` for _all_ buildings of this type
3. Calc the percent difference as 
```
((total_ghg - building_type_average_ghg) / building_type_average_ghg) * 100;
```

For some reason, previously I was using `total_ghg_emissions_intensity` but I don't know what this is, and it doesn't seem relevant here

**Comment by danrademacher** [comment]
Closing this in favor of specific issues
