### ISSUE TITLE
Re-enable call to action section links

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#56]
This should essentially be the reverse of #45 

Some additional details about how the links are formatted and displayed is here in [Links.md](https://github.com/GreenInfo-Network/seattle-building-dashboard/blob/master/docs/Links.md)

> The configuration for these are located in the [seattle.json](../src/cities/seattle.json) file. The data for the links are located in the [cityenergy-seattle carto account](https://cityenergy-seattle.carto.com/dashboard/datasets).

Links can be customized for buildings by building ID, or by building type. It looks as if all the links that are currently displayed are customized by building type. In all cases, there are only two or three links shown, as seen here: 

## Three link example (High-rise Multifamily)
[GH Pages Link](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2021?categories[0][field]=property_type&categories[0][other]=false&categories[0][values][]=High-Rise+Multifamily&layer=total_ghg_emissions&sort=total_ghg_emissions&order=desc&lat=47.62161&lng=-122.33716&zoom=15&building=50263&report_active=true)

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/62b35f56-3c19-4f5e-b0fd-b8afd5f28df1)

## Two link example (University) 
[GH Pages Link](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2021?categories[0][field]=property_type&categories[0][other]=false&categories[0][values][]=University&layer=total_ghg_emissions&sort=total_ghg_emissions&order=desc&lat=47.62161&lng=-122.33716&zoom=15&building=30&report_active=true)

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/dda65b53-5b17-4b9b-b74c-bc347f238551)

**Comment by tomay** [comment]
This is done and I've sent some details to the client about how these operate, and how to update them.

Note that per #59, when this goes to production, these CSV files will be served directly from src/data/links.csv 

That means any changes in this phase should be made directly to that CSV files (likely by us), not in CARTO by the client

**Comment by danrademacher** [comment]
They provided new copy:

NEW 

**Multifamily** 

1. Get a free energy savings assessment from an energy expert to identify energy saving opportunities for your property. Please contact Seattle City Light at [SCLEnergyAdvisor@seattle.gov](mailto:SCLEnergyAdvisor@seattle.gov) for more information.  
3. Financial incentives for energy efficiency upgrades are available for lighting, windows, insulation, and more. Financial incentives can cover up to 70% of project costs. https://www.seattle.gov/city-light/business-solutions/landlord-owner-agents/multifamily-building-energy-solutions 
 

**Commercial** 
1. Get a free energy savings assessment from an energy expert to identify energy saving opportunities and qualify your building for financial incentives on lighting, controls, HVAC and more. Please contact Seattle City Light at [SCLEnergyAdvisor@seattle.gov](mailto:SCLEnergyAdvisor@seattle.gov) for more information. 
2. Financial incentives for energy efficiency upgrades are available for lighting, controls, windows, insulation, appliances and more. Financial incentives can cover up to 70% of project costs. https://www.seattle.gov/city-light/business-solutions/large-commercial-and-industrial-business-solutions

There are screenshots and notes in this word doc: https://seattlegov.sharepoint.com/:w:/r/sites/OSE-External/_layouts/15/Doc.aspx?sourcedoc=%7B647DE2D2-0939-49EF-BFA4-5BE435C916CD%7D&file=Call%20to%20Action%20Text%2020230816.docx&action=default&mobileredirect=true

But I don't think they are needed to implement the above.

**Comment by tomay** [comment]
This raises a few questions.

1. I'll assume "Commercial" means use this same content for all building types that are not one of the three multifamily types

2. The way this is configured in CARTO is with the following components:
* Link header (the bold text as shown below)
* Link text (the text that follows the bold header)
* Button or "link" text
* Button href

I can mock this up in a copy of the existing links table and stage that on GH pages, but they may want to review the language choices, especially the first button which will I guess become a "mailto" link?

**Comment by tomay** [comment]
Ah, I see now that the link header and text are the same as the existing copy

**Comment by tomay** [comment]
Mostly set here
- HTML actually did work without modification, just that I had to restart the dev server
- Less clear about the choice for the link at the very bottom: 

Leave it blank, like this: 
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/0cf5c709-7a9b-4c0b-ba2c-0cfaf62ce761)

Or include a mailto link, like this: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/5a14d042-36b3-453e-9d22-74f4974bffe1)

**Comment by tomay** [comment]
Mike would like to try and custom handle "mailto" links to remove the link that currently shows beneath the button in (1).

**Comment by tomay** [comment]
So this kind of breaks the model of the links being composed of the same four components (header, text, link_text and link_href), and handled the same in a loop in the template. Nonetheless, I have added an exception to remove the link below the button if it includes "mailto:"

**Comment by tomay** [comment]
Deployed
