### ISSUE TITLE
Performance Benchmark Section

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#6]
This comes after #5 and #4. It's also a bigger chunk of work, but important to get it on the page so we can suss out data gaps and edges.

Main section:
![image](https://user-images.githubusercontent.com/1423200/144132511-38c65afd-1895-4896-9444-cfddd1eedb46.png)

Alert above:
![image](https://user-images.githubusercontent.com/1423200/144132562-c4666c1d-72a0-4236-b23d-69c57f7f9f86.png)

Note that the anchor link in the alert ties to the section below.

https://xd.adobe.com/view/fc56a1c7-ec9e-46c9-a352-63b9f05e276a-a905/

Terry will provide a text alert to replace the bar chart when a building has no EUI and thus no EUIt. Something like "Performance data not available for this building."

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201449333826980)

**Comment by tomay** [comment]
- [ ] Remove bubble chart: `/src/app/templates/scorecards/fueluse.html` and `/src/app/views/scorecards/charts/fueluse.js`
- [ ] Remove refs to `./charts/fueluse` in `/src/app/views/scorecards/building_scorecard.js`
- [ ] Add new template: `/src/app/templates/scorecards/performance_standard.html`
- [ ] Reference this template as `./charts/performance_standard` in `/src/app/views/scorecards/building_scorecard.js`

**Comment by tomay** [comment]
I don't think anchor links are going to work out of the back, the Backbone router takes over and tries to load
http://localhost:8080/#performance-standard-chart

With some work and R&D there could be a solution hacking the router, as shown here
https://stackoverflow.com/a/11675858

**Comment by danrademacher** [comment]
When cbps_flag is TRUE but cbps_euit is blank, hide the chart and show this message:
>We could not estimate an EUI Target for this building with the reported data. Contact energybenchmarking@seattle.gov if you have questions.

**Comment by danrademacher** [comment]
Forgot to note in the original issue that everything about the CBPS shows only for buildings where `cbps_flag` is true. If that flag is false, then the whole alert and the whole block, including title and everything should be hidden

**Comment by tomay** [comment]
#### Two conditional cases where we hide various Performance Chart components: 

1. Most commons is where cbps_flag is FALSE and all mention of this whole program should be hidden, like it doesn’t exist

    Example:  
    https://greeninfo-network.github.io/seattle-building-dashboard#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61983&lng=-122.33925&zoom=16&building=50263&report_active=true

2. Less common, where the cbps_flag is TRUE but the city lacks data to set the target

    Example: 
    https://greeninfo-network.github.io/seattle-building-dashboard#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61954&lng=-122.33657&zoom=16&building=465&report_active=true

**Comment by danrademacher** [comment]
When the building EUI is below the EUIt, make the bar be green:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1423200/145888822-7b69fd07-6c7f-44f3-9233-a69817a4bfb6.png">

**Comment by tomay** [comment]
Meets target:

![image](https://user-images.githubusercontent.com/740512/145902602-4055adfc-4cc2-489c-9dd7-bd7691426d0a.png)

Doesn't meet target: 

![image](https://user-images.githubusercontent.com/740512/145902638-4607aba3-acb6-42cf-8b0a-7200ac8c5d01.png)
