### ISSUE TITLE
Highlight selected building

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#67]
For both circle and boudling footprint, add a 3px `#000` stroke to the shape for selected building:

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/637609a5-d6b3-4966-a5c4-0908bf35da73)

Needs to track selection on zoom change back and forth between circles and footprints.

**Comment by tomay** [comment]
I've got a solution in place, that hooks into the existing render to re-render the highlights when crossing the zoom threshold. 

Despite that, it's pretty hacky. I'm definitely not fetching the footprint geojson per Backbone conventions. That said, doing so would be very time consuming, and it's not clear that its worth it. Especially given the aging infrastructure here per #63

**Comment by tomay** [comment]
Even in the current setup a building can have multiple footprints, which we need to handle from the GeoJSON response

An example is THE PITTSBURGH, 117 JOHN ST Seattle, WA 98109

**Comment by danrademacher** [comment]
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/c7aed73c-4925-486d-822a-cf5ccbf20dff)

https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2021?layer=total_ghg_emissions&sort=total_ghg_emissions&order=desc&lat=47.61960&lng=-122.35423&zoom=19&building=28006

Seems to work as expected. Can we close this out?

**Comment by tomay** [comment]
Done and deployed
