### ISSUE TITLE
Intro.js tutorial

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#69]
This actually looks pretty good.

Here's the mockup:
https://seattlegov.sharepoint.com/:p:/r/sites/OSE-External/_layouts/15/Doc.aspx?sourcedoc=%7BB72BE390-04E8-44AF-B15B-187B8872D964%7D&file=User%20Tutorial%20Mock%20Up.pptx&action=edit&mobileredirect=true

That might be annoying to access, so I saved to Drive, but we should be mindful that Mike could update the Sharepoint and Drive will not stay in sync.

https://docs.google.com/presentation/d/14Sbl9xQwP0rQSoAW2dVy0eLuF0fqKL4b?rtpof=true&usp=drive_fs

**Comment by danrademacher** [comment]
Notes from meeting:

* Can we get to the building report have a similar set?
   * Yes
* Might want to have it almost as second tutorial -- or at least some way to start it at that step for the building report
*

**Comment by tomay** [comment]
I’m not sure intro.js will do anything dynamic on the page. Although we might be able to, using [an approach like this](https://stackoverflow.com/a/53891665/1193155). 

Way back in 2018 I used [hopscotch](https://github.com/LinkedInAttic/hopscotch) to do something similar, we opened a panel that was by default closed, and then highlighted something within it. That project has been archived, but doesn’t mean we can’t use it.

There’s another one called [driver.js](https://driverjs.com/) that lets you do asynchronous things before calling the next step.

**Comment by danrademacher** [comment]
I guess the relevant example is the async tour?
https://driverjs.com/docs/async-tour

Looks highly functional, though it takes some imagination to apply their examples to real interfaces

**Comment by tomay** [comment]
The asnyc utilities of Driver seem to be working well so far. 

One limitation could be that we can only highlight a single element, using the bbox of that element. So a view like this, for example, won't be possible: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/d93bfef2-15a8-49bc-b523-1425548bad1b)

Here's what we get instead (the entire panel, not just the labels)

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/bd6e2367-104e-494b-9297-31e4bcc7ca0b)

**Comment by tomay** [comment]
Here's the splash screen so far: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/97bf96bf-82cd-485b-ae5e-755949d42f6c)

**Comment by danrademacher** [comment]
That's looking really nice! 

One thing I was thinking about after last meeting was that we need to make sure the splash is super accessible and easy for tab nav and screen reader, since they are using it to highlight accessible alternative

**Comment by tomay** [comment]
Good thinking! I added focus styles (projects of this vintage this often include a "reset" CSS to remove all default focus styles), increased the font size to 16px and made the close button a proper `<button>`

**Comment by tomay** [comment]
The tour is largely ready to review, however, I only realized far into the work how difficult it was to access the map from the tour. 

I might refactor the tour as a child of the map and building layer views. Sounds weird, but that way I'd have direct access to the map and map state, which is only available after the map loads (and needed here to reset x,y,z to the default after the last step). 

I'm working around this now with a 3 second timeout when I initialize the Splash and Tour, which is not great.

**Comment by tomay** [comment]
For now, I've deployed this to https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2021

We could leave it as is, or dive back in and try another approach for organizing it. My concern with the timeout is that if the map takes longer than 3 seconds to load, then the tour would break at that point.

**Comment by tomay** [comment]
Hmm, just realized you can have this happen, if loading a URL with a report open: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/893e0a0f-1718-4a7a-9d6d-4ec63f130d4b)

Maybe we just always click the back-to-map link after starting the tutorial?

**Comment by tomay** [comment]
Updated PPT mockup saved to Drive: 
https://docs.google.com/presentation/d/1pkCEZoNl8aa8RiQkIkS8FkY4aN4e5Elk/edit?usp=drive_link&ouid=112218622749960089733&rtpof=true&sd=true

**Comment by danrademacher** [comment]
Pulling over from Slack that I am somewhat concerned that the Launch Tutorial link does not repeat the splash page info, so there's no easy way to get that. But Tom is concerned that the user told us not to show them that panel, so why are we showing it to them and making them click again?

A both/and solution here would be to add to the FAQ, but when I tried that in [this branch](https://github.com/GreenInfo-Network/seattle-building-dashboard/commit/e0b298ac3d19165d2a7a460e2da6f58b2b9a4c96), the HTML for links is ignored.

My main concern here is that the accessibility information should be accessible even if I disable the tour.

**Comment by tomay** [comment]
To make this work, I had to double up on the interior quotes in `faq.csv`

```csv
cartodb_id,question,answer
18,What is this tool for?, Use this tool to explore building energy and greenhouse gas emissions performance data that is collected under Seattle’s energy benchmarking ordinance.
19,How else can I access this data?,"The Energy Benchmarking Map displays annual energy and GHG emissions data for buildings 20,000 square feet and larger, dating back to 2015. To access Seattle Energy Benchmarking data in a spreadsheet format, please visit the the <a href=""https://data.seattle.gov/browse?q=building%20energy%20benchmarking&sortBy=relevance&utf8=%E2%9C%93"">Seattle Open Data Portal</a>."
20,What accessibility accommodations are available?,"The City of Seattle encourages everyone to participate in its programs and activities. For disability accommodations or information in alternate formats, please contact <a href=""mailto:energybenchmarking@seattle.gov"">energybenchmarking@seattle.gov</a>."
```


![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/a84de811-ad13-46de-9c66-a072ce9420a4)

**Comment by tomay** [comment]
I had to remove references to LeftArrow from the [Driver source](https://github.com/kamranahmedse/driver.js/blob/master/src/driver.ts), rebuild, and include that here. 

So the left arrow is now inoperable, but right arrow continues to work as before

**Comment by tomay** [comment]
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/919fa79c-c1b4-4c40-9743-1900ac1888ad)


> This says it defaults to GHG emissions – though sometimes when I run the tutorial the map is actually toggled to show GHG intensity – can we force the tutorial to always show total GHG emissions for this step?

We need to both ensure that 
- [ ] Accordion is open to first panel
- [ ] Total GHG is selected
