### ISSUE TITLE
Overhauled GHG section

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#7]
New design:
![image](https://user-images.githubusercontent.com/1423200/144132930-619f6b00-3a58-40e0-9312-7ee82c111073.png)

Currently looks like this:
![image](https://user-images.githubusercontent.com/1423200/144133030-c5d4cd0d-795f-4494-a137-f2efac15bdc1.png)

The full-width bar charts are the same as the lower left ones in current build, except (a) they are wider and (b) the order of categories should always be electric, steam, gas.

Note that there is variant text that shows when a building is already 100% electric. For the three bullet points at the bottom and the link on right. Icons stay the same

> Congratulations! Your building is all electric and carbon neutral.
> 
> PLAN – Is your building as efficient as it can be?
> 
> REDUCE – Check out City Light’s incentives
> 
> RENEWABLES – Get even greener
> 
> https://www.seattle.gov/city-light/business-solutions/renewable-energy-services
>

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201449297223938)

**Comment by tomay** [comment]
"variant" described above is still TO DO

Also, we need some sort of page break when top blue alert is hidden (because no performance chart):

![image](https://user-images.githubusercontent.com/740512/145628833-9ca75e99-5f95-4fe9-a7b3-08532a1b3c2c.png)

**Comment by tomay** [comment]
The second chart on this one for COLMAN BUILDING is overflowing, as if the values are adding up to more than 100%:

![image](https://user-images.githubusercontent.com/740512/145658783-6e744168-ea15-4a92-b3f3-3887470f7a88.png)

Looks like they are running the correct values through a function `fixPercents()` which actually makes each measure 1% larger, for a total of 102%. Maybe some of them it actually fixes? 

![image](https://user-images.githubusercontent.com/740512/145659440-7b08a5fd-76df-44ab-90ed-e8fad2c58ccf.png)




The function itself is inscrutable, without comments: 
```javascript

    fixPercents: function(fuels, prop) {
      const values = fuels.map((d, i) => {
        const decimal = +((d[prop].pct_raw % 1));
        const val = Math.floor(d[prop].pct_raw);
        return {
          idx: i,
          val,
          iszero: val === 0,
          decimal: val === 0 ? 1 : decimal
        };
      }).sort((a, b) => {
        return b.decimal - a.decimal;
      });

      const sum = d3.sum(values, d => d.val);

      let diff = 100 - sum;

      values.forEach(d => {
        if (diff === 0) return;

        diff -= 1;
        d.val += 1;

        d.iszero = false;
      });
```

**Comment by tomay** [comment]
COURTYARD BY MARRIOTT - SEATTLE
100% Electric: 

![image](https://user-images.githubusercontent.com/740512/145905624-a2416eef-4013-44c7-86c8-c1d0910955d3.png)

Current threshold is 99% per Terry's comment in #4:
> You can use electricity_pct > 0.99 or something
