### ISSUE TITLE
Seattle Building Footprint Digitizing

### ISSUE THREAD

**Issue by DariyaGIN** [GreenInfo-Network/seattle-building-dashboard#70]
[Dashboard](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2021)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1DAyLq1XWCSxC5smWZMkNtcv0byxVxTPG/edit#gid=134238005)

1. Use the building Ids below to view the data on the dashboard website
2. Go to the spreadsheet, find the row with that building id, get the building address, and use google maps to preview the satellite image of the building
3. In ArcPro create a shapefile and digitize / create a polygon for the building outline as you see it in the satellite image (use the lat longs from the spreadsheet to get you to the correct location).  The shapefile should have a column "building_id" and record the associated building id for each geometry.

Digitize these Seattle Building IDs:
--
21231 - digitize building in NW corner
21616 - digitize school
49894 - digitize 4 buildings
50067

**Comment by DariyaGIN** [comment]
For Joseph to fix:

- 21231 - split, and remove everything but the NW corner

**Comment by joseph-stout** [comment]
> For Joseph to fix:
> 
> * 21231 - split, and remove everything but the NW corner

Fixed-- tool to break apart merged/multipoint polygons is "Explode" in ArcGIS Pro.

**Comment by DariyaGIN** [comment]
Great, here is a new list to digitize.  I have added details for how to digitize each one / what to look for specifically.

Dashboard Building ID | Notes
-- | --
21570 | Current shape in Seattle Dashboard is wrong (school was rebuilt recently).  Please use satellite to digitize correct footprint.
50175 | There are two L shaped buildings in this apt complex.  One is in the dashboard, one isn't.  Please digitize missing building (East one).
27774 | There are three buildings in this apt complex, two of them are already in the dashboard, but one is missing.  Please digitize the missing building (on satellite, it has a black rooftop like the other two, and it is on the West side of the other two).

**Comment by joseph-stout** [comment]
All new entries should be up to date. The file path to the updated shapefile is here: 

P:\proj_p_s\Seattle Building Dashboard\2023 update\DigitizingFootprints_20230921\DigitizedFootprints_20230926.shp

And the file path to the project (in case you want to tour around for QA) is here:
P:\proj_p_s\Seattle Building Dashboard\2023 update\DigitizingFootprints_20230921

**Comment by DariyaGIN** [comment]
For Joseph to fix: 
21321 - explode into mult. polygons, delete all but NW corner.
49894 - you digitized one of the four buildings, but there are three other buildings that need to be part of this (again, leave them as single polygons)
50245 - explode into mult. polygons
50309 - redo this one, just a single building
50177 - explode into mult. polygons

**Comment by joseph-stout** [comment]
21321- Exploded and deleted all but NW corner (View at Bitter Lake Apartments)
50245- Exploded into separate records (Cascade I and II Combined)
50177- Exploded into mult. records
50481-Exploded into mult. records (Sorento Flats)
49894- Added three buildings to make 4 total for Array Apartments
50309- Re-digitized single building and ensured the geometry calculated/ zoom-to fiunction works. 

Updated Shapefile location:
P:\proj_p_s\Seattle Building Dashboard\2023 update\DigitizingFootprints_20230921\DigitizedFootprints_20230926.shp
