### ISSUE TITLE
Building data address corrections

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#73]
Following Dariya review. 
https://docs.google.com/spreadsheets/d/1S3ftokz4nCtDrrEmpBPLNyr5fnd0YlbnjasbCqZTiHI/edit#gid=1932132457

These will need to be updated in CARTO, and then I should check with Mike to see if he needs to update these upstream somewhere. Otherwise, I could imagine the same errors might come back with every update

**Comment by danrademacher** [comment]
Is this still relevant? Or maybe replaced by #87 ?

**Comment by tomay** [comment]
Still relevant. There's still one item to do here, and that's on this line: 
https://docs.google.com/spreadsheets/d/1S3ftokz4nCtDrrEmpBPLNyr5fnd0YlbnjasbCqZTiHI/edit#gid=1932132457&range=12:12

But I'm waiting for the final data to be all merged and ready to go on CARTO before I make that change. 

I do need to also email Mike with that same info, which I will do right now.

**Comment by tomay** [comment]
Emailed this to Mike 12/1

**Comment by tomay** [comment]
This has been changed in the latest 2022 data, and I'm not sure if we should update it for years 2017-2021 as well. 

I'm going to guess no, and close this as complete
