### ISSUE TITLE
Energy Use compared to Average (compare chart)

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#8]
New design:
![image](https://user-images.githubusercontent.com/1423200/144135112-e215407f-ede9-4e61-ace7-7d40e66986de.png)

Current look:
![image](https://user-images.githubusercontent.com/1423200/144135152-f344e8dc-10f6-401f-b7e1-d84a0a926b8d.png)

* Change location of toggle
* Update font weights and sizes
* Vertically shorter
* New label treatment

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201449407610439)

**Comment by tomay** [comment]
Some challenges with the new label treatment

### Vertically shorter chart
1) In the existing app, the building label is above the chart to help minimize collision. I think they did this to be sure that the building label will have space (and be prominent). 
2) The chart has to have a fixed height. In the new design, we don't know a-priori which bar a given label will be above - it could be the shortest bar or it could be the tallest. We'd still have to leave enough white space above the chart to allow for either. 

The La Quinta example above highlights these issues. The labels are on the tallest bars, so there has to be a similar amount of white space above the chart to fit them.

 ### New label treatment
1) The design shows the average label to the left of its line, and the building label to the right of its line. But the order of these two bars is variable. To achieve this for all buildings, we would have to figure out which one comes first, and adjust the placement of the text relative to the line accordingly

**Comment by danrademacher** [comment]
- [ ] Move the circle and text below it on left up nearer to title
- [ ] Change the chart building label to 14px

**Comment by tomay** [comment]
Just noticed that these measures are different: 

![image](https://user-images.githubusercontent.com/740512/146281203-ad44121b-eac2-4f2b-8789-e5b1e85dcbc6.png)

![image](https://user-images.githubusercontent.com/740512/146281239-cc21eaf5-cc57-4c55-ab56-af8a0038851d.png)

Chart is probably not using `eui_wn`

**Comment by tomay** [comment]
Found it in `getViewField`, called by `getCompareChartBinnedData` called by `prepareCompareChartData` in `processBuilding` and passed as `chartData` to `renderCompareChart`

changed to: 
```
  getViewField: function(view) {
    return view === 'eui' ? 'site_eui_wn' : 'energy_star_score';
  },
```

That fixes the value, but throws the colors off: 

![image](https://user-images.githubusercontent.com/740512/146282604-d01c5de3-a098-40db-941e-7da709bae047.png)

**Comment by tomay** [comment]
Okay, there were two other places with hard-coded `site_eui`. Changed both to `site_eui_wn` but only one seems to do anything
```javascript
if (compareField === 'site_eui_wn') {
        selectedColor = this.getCompareChartColor(data, thresholds, id);
```

**Comment by danrademacher** [comment]
Remaining here as of yesterday:
- [ ] Move the symbol and text to left of chart up closer to top of chart

This looks done?
<img width="999" alt="image" src="https://user-images.githubusercontent.com/1423200/146451637-943790a7-9c42-44a2-854e-99c0d6e8c904.png">

**Comment by tomay** [comment]
yes, done!
