### ISSUE TITLE
Add tooltip with building name and ID on hover

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#80]
This would apply to the points and footprints

See this example:
https://github.com/CartoDB/carto.js/blob/develop/examples/TheHobbitLocations/js/app.js

Though that example relies on a callback from `createVis`, which we're not using here. So we'll have to feel our way though this using 8 year old docs and examples

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208128717878127)

**Comment by tomay** [comment]
One big issue, footprints do not have any attributes, apart from an id back to the building data (and this has a different name than it does on the building data)

So this is not going to be straightforward at all

**Comment by tomay** [comment]
Okay, I've got a roll-your-own tooltip in place: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/8f2727a9-e5f9-413c-823f-4049710c30dc)

@danrademacher any thoughts on style or layout? The ID in particular, I'm not sure what treatment makes sense for that. For now it's just pasted in as 
```javascript
`${name}, ${id}`
```

**Comment by tomay** [comment]
Inspired by the map popup, I went ahead and gave the tooltip look a similar treatment for Name and ID:

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/d550ed91-c9a0-4cc5-9612-bb753d0c93cb)

Feel free to reopen if this needs anything else

**Comment by danrademacher** [comment]
looks excellent!

**Comment by tomay** [comment]
On production there is an offset, most likely due to this being in an iframe with a header: 

- [ ] Check if we are in an iframe
- [ ] If we are, add/subtract an offset equal to the header height of 136px

**Comment by tomay** [comment]
This is currently testing for an iframe, but it turns out that we aren't in an iframe, so we need another test so this looks good/works on both staging and production. Could check href for seattle.gov

**Comment by tomay** [comment]
Trying a more direct approach, that uses Leaflet's `latlngToContainerPoint` to more directly (I hope) get at the position of the hovered element.

**Comment by tomay** [comment]
It looks like the root cause of the offset is relative positioning added to `.main-container` on the Seattle side:

![image](https://github.com/user-attachments/assets/363b0831-063e-4074-892c-ae7c68d31b2e)

Won't know for sure if this latest change will fix it, but I can mock that on the staging site, and the tooltips follow: 

![image](https://github.com/user-attachments/assets/85affb09-6c4a-4728-9d64-763e37047458)

Closing for now, we can reopen if needed following production deploy
