### ISSUE TITLE
New message for No Data (out of compliance) buildings

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/seattle-building-dashboard#84]
Existing: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/c40fba94-342b-4733-9f2e-01b73efb4b0c)

New: 

<img width="243" alt="image" src="https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/18aba704-1257-4d60-bc6f-6f38a1a1f37e">

New copy:

Out of Compliance
As of the last quarterly update to this map, the City of Seattle has not received complete, valid energy data for this property in this reporting year. If this is your building, please visit the [Energy Benchmarking Instructions page](https://www.seattle.gov/environment/climate-change/buildings-and-energy/energy-benchmarking/instructions) or contact energybenchmarking@seattle.gov to bring your building into compliance.

* Add this message for records without EUI

* EnergyStar score is complex:
    Just take out the alert for this being absent

**Comment by tomay** [comment]
From the code, it looks like there is supposed to be something similar happening on Building Reports when there is no data. 

But for now it's doing this: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/56523551-79ea-42a2-b8a6-a060033c666d)

With the following error: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/dd38f078-6b62-41ff-9342-23393cd88f60)

**Comment by tomay** [comment]
Building report is at least working now. That looks like this: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/4fe2228b-703a-4673-89a6-8e93c3b32d73)

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/a7c87b42-411a-44be-aed6-9e5e55ac05a7)

This one is suspect "100% lower than average" - is that because it's comparing to 0? 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/d09a3440-c1a1-449e-b2e2-0a87db79cd1f)

**Comment by tomay** [comment]
New nodata popup is shaping up like so: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/5a55e848-9b67-40e4-86e7-c708e2a3c90f)

**Comment by tomay** [comment]
Here's what it looks like when there _is_ an EUI, but there is not an Energy Star Score: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/3765c566-b608-402f-956d-8642b74086ab)

**Comment by tomay** [comment]
New ask: disable VIEW BUILDING REPORT button/make grey when there is no EUI

**Comment by tomay** [comment]
Looks like the `disabled` attribute already has a disabled style, and includes `cursor: not-allowed` 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/9d2bdde5-a6bf-43eb-a828-454f2bd18ced)

**Comment by danrademacher** [comment]
With that last change, this is done
