### ISSUE TITLE
UW campus footprint work

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#86]
As part of our Campus data completion, client wants us to at least get the UW main campus building outlintes sorted.

So we would replace this giant shape:
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/62615d1f-ea48-48b7-9e89-d723f95d1faf)

With all the child buildings inside that shape.

Mike says that UW will supply a shapefile of the related buildings before Thanskgiving. We shall see!

This is building id `49967` so in theory, if the SHP really does include only footprints on that one campus, we could just export them all as individual footprint records with the same Dashboard ID, though we'd also need to remove the dozen or so buildings that have their own scores already:
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/b871c5e1-0c41-449f-81ce-64282a4ec177)

**Comment by danrademacher** [comment]
Mike sent us a UW shapefile:
https://drive.google.com/open?id=1MPf1lxNOZwyP6gFS1jVeSgu4nq22Do7k&usp=drive_fs

This includes data that is outside the above blue trapezoid, but it is only the main campus, so I _think_ it should be susceptible to a bulk update solution
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/94e35250-a0f3-4770-94fb-5d191e426013)

In concept, we would want to do the following:
1. Load the UW shapefile and default to including all outlines in the SHP with Dashboard ID `49967`
2. Remove from this new layer any building that already exists in the building footprint table -- this will have to be by some spatial comparison, since I don't think there are IDs or other fields to match. 
3. Add remaining new UW shapes to the main footprints table

**Comment by danrademacher** [comment]
Huh, this just in from Mike:
>﻿﻿One quick note – within the last couple months, a bunch of those miscellaneous standalone UW buildings were brought under the main campus record in our database – **as represented in the latest campus parent-child crosswalk Excel file**. In other words, in the latest benchmarking data pull provided for 2022, I don’t think those seemingly random standalones will be there anymore. Some UW buildings legitimately should stand apart from the campus benchmarking record, but we need to make sure that we’re capturing the current relationship.

Oof. I am not sure how we will parse this, to be honest.  I keep hoping we can avoid slogging through the Excel file, but maybe not.

So we have 132 child buildings with the UW parent ID, [as shown in SharePoint](https://seattlegov.sharepoint.com/:x:/r/sites/OSE-External/_layouts/15/Doc.aspx?sourcedoc=%7B7163B239-733F-4810-B174-65E01B602402%7D&file=Campus%20Relationships%20Update%2020231117.xlsx&action=default&mobileredirect=true).

Meanwhile, the shapefile from UW has 351 features in it. 

On a quick scan, the NAME field is not consistently similar between the two files. The ADDRESS field looks more promising, though there will be cases, possibly many cases, where multiple buildings in either source share the same address.

**Comment by danrademacher** [comment]
Discussing with Mike on 11/27:
* There will definitely be buildings in the UW shapefile, like a hospital campus, that should not be part of the main campus
* Start with address matching and see what's left

**Comment by danrademacher** [comment]
All the addresses for Seattle buildings are here:
https://data-seattlecitygis.opendata.arcgis.com/datasets/SeattleCityGIS::addresses-maf/explore?location=47.654016%2C-122.306944%2C16.00

**Comment by danrademacher** [comment]
Split the task:
* Look first inside the main campus shape and make sure that is al accounted for
* Only then look at the buildings outside the main campus shape

**Comment by danrademacher** [comment]
That's 11 building footprints
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/8759584f-9733-4fac-9021-0702690f0e98)

```csv
buildingid
"49716"
"49975"
"49983"
"49971"
"49969"
"49984"
"49968"
"49981"
"49972"
"49977"
"29390"
```

So a check for these would be to see if they show up in the latest data.

**Comment by danrademacher** [comment]
Maike asked me to send him those 4 building ids so he can check them. He already found that `49969` should  not be exporting from upstream. If the others are that way too, then we should be able to complete this core task very quickly. He's fine letting go of the rest of the "non-core" buildings for this phase.

**Comment by danrademacher** [comment]
Mike says the only one that should stay separate is this housing building:
https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2022?layer=total_ghg_emissions&sort=total_ghg_emissions&order=desc&lat=47.65570&lng=-122.31242&zoom=14&building=29390

So we can delete these ten footprints, and then this task should be complete and ready to load into CARTO:
```
49716 
49975 
49983 
49971 
49969 
49984 
49968 
49981 
49972 
49977 
```

**Comment by danrademacher** [comment]
Looks good running locally:
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/f5dcd890-1a3c-48c7-8d03-b7791e97835f)

Confusing why UW is out of compliance, but I hope that will be solved by the final data update from Mike

**Comment by danrademacher** [comment]
Unsaved notes: I deleted the 10 we needed to delete and saved all data back to P with a little reorganization.

Most current footprints are here:
P:\proj_p_s\Seattle Building Dashboard\2023 update\seattle_building_outlines_2023_updated_20231204

I uploaded to CARTO, though I had to delete the `cartodb_id` field to do so, since QGIS saved it as a float (and it actually doesn't matter if those get reassigned every time we upload). The copy on P still has the `cartodb_id`

It's on CARTO here:
https://cityenergy-seattle.carto.com/dataset/seattle_building_outlines_2023_1204

**Comment by danrademacher** [comment]
Huh, somehow I ended up with overlapping buildings, which I saw when Tom updated the data from Mike.

The one on top here should have been deleted:

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/bf043cea-d9fc-4bd5-91af-f525df128bec)

And now it is gone from P and CARTO.

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/7a31ab25-1621-4246-bd10-74596cc94cd5)

**Comment by danrademacher** [comment]
Email to Mike:

> I discovered an issue where one buildings are still stacked and likely should be part of the main campus:
> 49973, UW - FOEGE BUILDING (genome sciences)
> That one causes a problem where it is stacked on top of the main campus record, since they have the same street address.
> 
> Can you confirm if that is included in the main campus record?
> 
> If so, I will delete the record from CARTO for both the energy data and footprints, and you could delete upstream.
> 
> At that point, Phase 2 will be complete.

**Comment by tomay** [comment]
In addition to Foege (above) we have similar issues for two additional buildings on UW Main campus: Hitchcock Hall and Molecular Engineering & Sciences Building

To fix, using a table of UW Seattle Buildings, here is the SQL applied to the table `seattle_building_outlines_2023_1204`: 

```sql
-- FOEGE
-- ADD CORRECT FP FOR 2022 AS PART OF UW MAIN
INSERT INTO public.seattle_building_outlines_2023_1204 SELECT 4779 AS cartodb_id, the_geom, null, null, null from uwseattlebuildings where FacName = 'William H. Foege Genome Sciences'
UPDATE public.seattle_building_outlines_2023_1204 SET source = 'UW GIS data FacNum 4058 FacCode GNOM FacName William H. Foege Genome Sciences' WHERE cartodb_id = 4779

-- HITCHCOCK
-- ADD CORRECT FP FOR 2022 AS PART OF UW MAIN
-- ADD DUPLICATE FOR 2017-2022 STANDALONE BENCHMARK DATA
INSERT INTO public.seattle_building_outlines_2023_1204 SELECT 4780 AS cartodb_id, the_geom, null, null, null from uwseattlebuildings where FacName = 'Hitchcock Hall'
UPDATE public.seattle_building_outlines_2023_1204 SET buildingid = 49977, source = 'UW GIS data FacNum 1324 FacCode HCK FacName Hitchcock Hall' WHERE cartodb_id = 4781
INSERT INTO public.seattle_building_outlines_2023_1204 SELECT 4781 AS cartodb_id, the_geom, null, null, null from uwseattlebuildings where FacName = 'Hitchcock Hall'
UPDATE public.seattle_building_outlines_2023_1204 SET buildingid = 49967, source = 'UW GIS data FacNum 1324 FacCode HCK FacName Hitchcock Hall' WHERE cartodb_id = 4780

-- MOL
-- DELETE EXISTING FOOTPRINT AND 2022 BENCHMARK DATA
-- ADD CORRECT FP FOR 2022
-- ADD DUPLICATE FP FOR 2017-2022 STANDALONE BENCHMARK DATA
DELETE FROM public.seattle_building_outlines_2023_1204 WHERE buildingid = 41927
INSERT INTO public.seattle_building_outlines_2023_1204 SELECT 4782 AS cartodb_id, the_geom, null, null, null from uwseattlebuildings where FacName = 'Molecular Engineering & Sciences Building'
UPDATE public.seattle_building_outlines_2023_1204 SET buildingid = 49967, source = 'UW GIS data FacNum 6105 FacCode MOL	Molecular Engineering & Sciences Building' WHERE cartodb_id = 4782
INSERT INTO public.seattle_building_outlines_2023_1204 SELECT 4783 AS cartodb_id, the_geom, null, null, null from uwseattlebuildings where FacName = 'Molecular Engineering & Sciences Building'
UPDATE public.seattle_building_outlines_2023_1204 SET buildingid = 41927, source = 'UW GIS data FacNum 6105 FacCode MOL	Molecular Engineering & Sciences Building' WHERE cartodb_id = 4783
``` 

I also fixed the address and lat/lngs for Foege and Hitchcock in the benchmarking data and reuploaded that to CARTO

**Comment by tomay** [comment]
Copy of the latest (final?) building footprint table on CARTO here:

https://drive.google.com/file/d/1NTLfzJOfuhJw8jz8lXklY3YbAt5p7a8j/view?usp=drive_link

**Comment by tomay** [comment]
Note I've renamed the latest footprint table on CARTO to `seattle_building_outlines_2022`
https://cityenergy-seattle.carto.com/dataset/seattle_building_outlines_2022

To be consistent with the names for prior data releases

**Comment by tomay** [comment]
That change is done in `seattle.json` and committed and deployed. With that I believe we're done with footprints and campuses for this round

**Comment by tomay** [comment]
There is still a row for `UW - FOEGE BUILDING (genome sciences)` in the 2022 data, so we need to delete that: 
`DELETE FROM public.seattle_buildings_2022_update where property_name = 'UW - FOEGE BUILDING (genome sciences)' and year = 2022`

Also, the footprint for this should be comprised of two buildings from the UW Campus Data, not the one genome sciences. We already have a shape for this on board that we can reuse: 

![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/d77318b2-e627-4969-9fbe-0547646f819c)

```
DELETE FROM public.seattle_building_outlines_2022 where cartodb_id = 4779
INSERT INTO public.seattle_building_outlines_2022 SELECT 4784 AS cartodb_id, the_geom, null, null, null FROM public.seattle_building_outlines_2022 WHERE buildingid=49982;
UPDATE public.seattle_building_outlines_2022 SET buildingid = 49967 where cartodb_id = 4784
```

Done: 
![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/740512/74b599ef-40a2-4cc7-87f8-b2560efd2fc4)
