### ISSUE TITLE
Update building footprints on CARTO from data on server

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#87]
File can be downloaded here:
https://www.dropbox.com/t/dWhJtQJG1fqc2lTw

The source is here:
P:\proj_p_s\Seattle Building Dashboard\2023 update\seattle_building_outlines_2023_updated.shp

Per #85 this is the final round of updates.

**Comment by tomay** [comment]
I've made a new table on CARTO for these, so we can stage and test: 
https://cityenergy-seattle.carto.com/dataset/seattle_building_outlines_2021_final

**Comment by tomay** [comment]
Looks good to me - @DariyaGIN would you be able to pull up the footprints and check a few that you know have changed? 

https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2022
