### ISSUE TITLE
Two buildings on top of each other?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#89]
Mike:

> I found a weird situation in the test environment. It looks like the same shape is in compliance/out of compliance and corresponding to multiple buildings. It seems like it’s simultaneously crosshatched/normal.
>  
> ![image](https://github.com/GreenInfo-Network/seattle-building-dashboard/assets/1423200/caccd53f-c114-4e71-ac26-fc813a315841)

Seems like there's two shapes on top of each other?

**Comment by tomay** [comment]
I notice in those screenshots above that one is called "WESTWOOD VILLAGE - BLDG B" and the other is "WESTWOOD VILLAGE - BUILDING F"

Seems likely this is two footprints directly overlapping each other? It's also possible they are separately benchmarked, but with similar/same lat-lngs

**Comment by tomay** [comment]
We might not be able to clear this up during this phase of work. 

But one approach would be to query for building footprints that have X% spatial overlap

**Comment by tomay** [comment]
Closing as not in scope for this phase of work
