### ISSUE TITLE
Energy use trends (shift)

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#9]
New design:
![image](https://user-images.githubusercontent.com/1423200/144135349-240e245a-eb9a-43a2-8055-8b43b8171a75.png)

Currently looks like:
![image](https://user-images.githubusercontent.com/1423200/144135375-252ce264-5501-4676-9828-6228f16da8b8.png)

Minimal changes:

* Font weights and sizes
* Vertical compression with title and text in left column with icon vs above those

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201449364905012)

**Comment by tomay** [comment]
Do they want to drop the labels ("Building Type Average", "WASH MUTUAL TOWER (1201 THIRD AVE)"  shown on the far right here? 

They are not in the design, but that could just be an oversight

![image](https://user-images.githubusercontent.com/740512/145893953-cdcbcb52-42ea-45f3-993f-18e1cfdc1127.png)

**Comment by danrademacher** [comment]
@tsinn can you weigh in on those labels?

**Comment by tsinn** [comment]
Sorry - I think it's helpful to include just like you've done, Tom. Looks good!

**Comment by tomay** [comment]
I think they are calculating percent change wrong here: 

![image](https://user-images.githubusercontent.com/740512/145898589-01820f8b-3b78-45a8-beaf-7242501d714d.png)

```javascript
    const previousValue = yearData[0].val;
    const selectedValue = yearData[1].val;
    return ((selectedValue - previousValue) / selectedValue) * 100;
```

They are dividing the difference by the current value, not the initial value

The formula should be:
`( initial_value - current_value ) / initial_value * 100`

**Comment by danrademacher** [comment]
Simple real-life example from last comment

`(3-2)/3 = 33%`
vs
`(3-2)/2=50%`
